(function(g){var window=this;var WBa=function(a,b){return g.Ub(a,b)},m6=function(a){g.Fm(a,"zx",g.vb());
return a},n6=function(a,b,c){g.ya(c)||(c=[String(c)]);
g.Im(a.g,b,c)},XBa=function(a,b){var c=[];
g.uk(b,function(a){try{var b=g.fD.prototype.l.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.t(b)?g.eD(b)&&c.push(a):c.push(a)},a);
return c},YBa=function(a,b){var c=XBa(a,b);
(0,g.B)(c,function(a){g.fD.prototype.remove.call(this,a)},a)},ZBa=function(a){if(a.zd){if(a.zd.locationOverrideToken)return{locationOverrideToken:a.zd.locationOverrideToken};
if(null!=a.zd.latitudeE7&&null!=a.zd.longitudeE7)return{latitudeE7:a.zd.latitudeE7,longitudeE7:a.zd.longitudeE7}}return null},$Ba=function(a,b,c,d){var e=new g.wm(null,void 0);
a&&g.xm(e,a);b&&g.ym(e,b);c&&g.zm(e,c);d&&g.Am(e,d);return e},aCa=function(a){g.bG[a]&&(a=g.bG[a],(0,g.B)(a,function(a){g.$F[a]&&delete g.$F[a]}),a.length=0)},bCa=function(a){var b=g.ZF();
if(b)if(b.clear(a),a)aCa(a);else for(var c in g.bG)aCa(c)},o6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.o=!1;this.capabilities=new window.Set;this.experiments=new window.Set;this.theme="u";new g.qm;this.g=this.l="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",cCa(this,a.capabilities||""),dCa(this,a.experiments||""),this.l=a.remoteControllerUrl||"",
this.g=a.localChannelEncryptionKey||"")},cCa=function(a,b){a.capabilities.clear();
(0,g.Kd)(b.split(","),g.Ea(WBa,eCa)).forEach(function(b){a.capabilities.add(b)})},dCa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(b){a.experiments.add(b)})},p6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},q6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},fCa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},gCa=function(a){return new p6(a)},hCa=function(a){return g.ya(a)?(0,g.G)(a,gCa):[]},r6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},s6=function(a){return g.ya(a)?"["+(0,g.G)(a,r6).join(",")+"]":"null"},t6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},iCa=function(a){return(0,g.G)(a,function(a){return{key:a.id,
name:a.name}})},u6=function(a,b){return g.Ja(a,function(a){return a||b?!a!=!b?!1:a.id==b.id:!0})},v6=function(a,b){return g.Ja(a,function(a){return q6(a,b)})},jCa=function(){var a=(0,g.VG)();
a&&YBa(a,a.g.Od(!0))},w6=function(){var a=g.YG("yt-remote-connected-devices")||[];
g.fb(a);return a},kCa=function(a){if(g.Pa(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.G)(a,function(a,b){return 0==b?a:a.substring(c.length)})},lCa=function(a){g.XG("yt-remote-connected-devices",a,86400)},y6=function(){if(x6)return x6;
var a=g.YG("yt-remote-device-id");a||(a=t6(),g.XG("yt-remote-device-id",a,31536E3));for(var b=w6(),c=1,d=a;g.Oa(b,d);)c++,d=a+"#"+c;return x6=d},z6=function(){var a=w6(),b=y6();
g.Oa(a,b);g.$G()&&g.ib(a,b);a=kCa(a);if(g.Pa(a))try{g.IG("remote_sid")}catch(c){}else try{g.HG("remote_sid",a.join(","),-1)}catch(c){}},mCa=function(){return g.YG("yt-remote-session-browser-channel")},nCa=function(){return g.YG("yt-remote-local-screens")||[]},oCa=function(){g.XG("yt-remote-lounge-token-expiration",!0,86400)},pCa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.G)(nCa(),function(a){return a.loungeToken}),c=(0,g.G)(a,function(a){return a.loungeToken});
(0,g.cm)(c,function(a){return!g.Oa(b,a)})&&oCa();
g.XG("yt-remote-local-screens",a,31536E3)},qCa=function(a,b){g.XG("yt-remote-session-browser-channel",a);
g.XG("yt-remote-session-screen-id",b);var c=w6(),d=y6();g.Oa(c,d)||c.push(d);lCa(c);z6()},A6=function(a){a||(g.ZG("yt-remote-session-screen-id"),g.ZG("yt-remote-session-video-id"));
z6();a=w6();g.Ta(a,y6());lCa(a)},rCa=function(){if(!B6){var a=g.qD();
a&&(B6=new g.$C(a))}return B6?!!B6.get("yt-remote-use-staging-server"):!1},sCa=function(){var a=window.document.createElement("a");
g.Yc(a,"https://www.gstatic.com/cv/js/sender/v1/cast_sender.js");a=a.href.replace(/^[a-zA-Z]+:\/\//,"//");return"js-"+g.zb(a)},tCa=function(a,b){var c=g.Dd("SCRIPT");
c.id=a;c.onload=function(){b&&(0,window.setTimeout)(b,0)};
c.onreadystatechange=function(){switch(c.readyState){case "loaded":case "complete":c.onload()}};
g.$c(c,g.ce("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"));var d=window.document.getElementsByTagName("head")[0]||window.document.body;d.insertBefore(c,d.firstChild);return c},uCa=function(){var a=sCa(),b=window.document.getElementById(a),c=b&&g.kF(b,"loaded");
c||b&&!c||(b=tCa(a,function(){g.kF(b,"loaded")||(g.jF(b,"loaded","true"),g.fG(a),g.ZD(g.Ea(bCa,a),0))}))},C6=function(a){return!!window.document.currentScript&&(-1!=window.document.currentScript.src.indexOf("?"+a)||-1!=window.document.currentScript.src.indexOf("&"+a))},vCa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},D6=function(a){a.length?wCa(a.shift(),function(){D6(a)}):E6()},xCa=function(a){return"chrome-extension://"+a+F6},wCa=function(a,
b,c){var d=window.document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(window.document.head||window.document.documentElement).appendChild(d)},G6=function(a){return 0<=window.navigator.userAgent.indexOf(a)},E6=function(){var a=vCa();
a&&a(!1,"No cast extension found")},H6=function(){if(yCa){var a=2,b=vCa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;wCa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",E6,c)}},zCa=function(){var a=window.__gCrWeb&&window.__gCrWeb.message&&window.__gCrWeb.message.invokeOnHost;
a&&(H6(),a({command:"cast.sender.init"}))},ACa=function(){H6();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);D6(["//www.gstatic.com/eureka/clank/"+(a?(0,window.parseInt)(a[1],10):0)+F6,"//www.gstatic.com/eureka/clank"+F6])},I6=function(a,b,c){g.K.call(this);
this.C=null!=c?(0,g.z)(a,c):a;this.ed=b;this.B=(0,g.z)(this.JI,this);this.g=!1;this.l=0;this.o=this.ya=null;this.A=[]},J6=function(){},K6=function(a,b,c,d){this.g=a;
this.o=b;this.D=c;this.C=d||1;this.A=45E3;this.W=new g.Mm(this);this.l=new g.tg;this.l.setInterval(250)},CCa=function(a,b,c){a.uj=1;
a.Zg=m6(b.clone());a.Ai=c;a.B=!0;BCa(a,null)},L6=function(a,b,c,d,e){a.uj=1;
a.Zg=m6(b.clone());a.Ai=null;a.B=c;e&&(a.iD=!1);BCa(a,d)},BCa=function(a,b){a.ck=(0,g.F)();
M6(a);a.yh=a.Zg.clone();n6(a.yh,"t",a.C);a.hm=0;a.Qc=a.g.ar(a.g.Xl()?b:null);0<a.Ir&&(a.Yo=new g.Uk((0,g.z)(a.wE,a,a.Qc),a.Ir));a.W.T(a.Qc,"readystatechange",a.hU);var c=a.bi?g.bc(a.bi):{};a.Ai?(a.Np="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.Qc.send(a.yh,a.Np,a.Ai,c)):(a.Np="GET",a.iD&&!g.zd&&(c.Connection="close"),a.Qc.send(a.yh,a.Np,null,c));a.g.qf(1)},FCa=function(a,b,c){for(var d=!0;!a.Nh&&a.hm<c.length;){var e=DCa(a,c);
if(e==N6){4==b&&(a.ah=4,O6(15),d=!1);break}else if(e==ECa){a.ah=4;O6(16);d=!1;break}else P6(a,e)}4==b&&0==c.length&&(a.ah=1,O6(17),d=!1);a.wf=a.wf&&d;d||(Q6(a),R6(a))},DCa=function(a,b){var c=a.hm,d=b.indexOf("\n",c);
if(-1==d)return N6;c=Number(b.substring(c,d));if((0,window.isNaN)(c))return ECa;d+=1;if(d+c>b.length)return N6;var e=b.substr(d,c);a.hm=d+c;return e},HCa=function(a,b){a.ck=(0,g.F)();
M6(a);var c=b?window.location.hostname:"";a.yh=a.Zg.clone();g.Fm(a.yh,"DOMAIN",c);g.Fm(a.yh,"t",a.C);try{a.xf=new window.ActiveXObject("htmlfile")}catch(n){Q6(a);a.ah=7;O6(22);R6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in S6)k=S6[l];else if(l in GCa)k=S6[l]=GCa[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=
m.toString(16).toUpperCase()}k=S6[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}d+="</body></html>";c=g.ad(g.vc("b/12014412"),d);a.xf.open();a.xf.write(g.Sc(c));a.xf.close();a.xf.parentWindow.m=(0,g.z)(a.nT,a);a.xf.parentWindow.d=(0,g.z)(a.uC,a,!0);a.xf.parentWindow.rpcClose=(0,g.z)(a.uC,a,!1);c=a.xf.createElement("DIV");a.xf.parentWindow.document.body.appendChild(c);d=g.Ic(a.yh.toString());d=g.pb(g.Fc(d));d=g.ad(g.vc("b/12014412"),'<iframe src="'+d+'"></iframe>');c.innerHTML=g.Sc(d);
a.g.qf(1)},M6=function(a){a.rv=(0,g.F)()+a.A;
ICa(a,a.A)},ICa=function(a,b){if(null!=a.wk)throw Error("WatchDog timer not null");
a.wk=T6((0,g.z)(a.DT,a),b)},U6=function(a){a.wk&&(g.w.clearTimeout(a.wk),a.wk=null)},R6=function(a){a.g.Dy()||a.Nh||a.g.Jo(a)},Q6=function(a){U6(a);
g.bf(a.Yo);a.Yo=null;a.l.stop();g.Sm(a.W);if(a.Qc){var b=a.Qc;a.Qc=null;b.abort();b.dispose()}a.xf&&(a.xf=null)},P6=function(a,b){try{a.g.nC(a,b),a.g.qf(4)}catch(c){}},KCa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;JCa(a,b,function(e){e?c(!0):g.w.setTimeout(function(){KCa(a,b,c,d,f)},f)})}},JCa=function(a,b,c){var d=new window.Image;
d.onload=function(){try{V6(d),c(!0)}catch(e){}};
d.onerror=function(){try{V6(d),c(!1)}catch(e){}};
d.onabort=function(){try{V6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{V6(d),c(!1)}catch(e){}};
g.w.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
d.src=a},V6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},LCa=function(a){this.g=a;
this.l=new J6},MCa=function(a){var b=W6(a.g,a.Ck,"/mail/images/cleardot.gif");
m6(b);KCa(b.toString(),5E3,(0,g.z)(a.UH,a),3,2E3);a.qf(1)},Y6=function(a){var b=a.g.H;
if(null!=b)O6(5),b?(O6(11),X6(a.g,a,!1)):(O6(12),X6(a.g,a,!0));else if(a.pe=new K6(a,void 0,void 0,void 0),a.pe.bi=a.Gr,b=a.g,b=W6(b,b.Xl()?a.al:null,a.Hr),O6(5),!g.xd||g.rc(10))n6(b,"TYPE","xmlhttp"),L6(a.pe,b,!1,a.al,!1);else{n6(b,"TYPE","html");var c=a.pe;a=!!a.al;c.uj=3;c.Zg=m6(b.clone());HCa(c,a)}},Z6=function(a,b,c){this.g=1;
this.l=[];this.A=[];this.B=new J6;this.F=a||null;this.H=null!=b?b:null;this.C=c||!1},NCa=function(a,b){this.g=a;
this.map=b;this.context=null},OCa=function(a){g.df.call(this,"statevent",a)},PCa=function(a,b){g.df.call(this,"timingevent",a);
this.size=b},QCa=function(a){g.df.call(this,"serverreachability",a)},TCa=function(a){RCa(a);
if(3==a.g){var b=a.Jl++,c=a.En.clone();g.Fm(c,"SID",a.o);g.Fm(c,"RID",b);g.Fm(c,"TYPE","terminate");$6(a,c);b=new K6(a,a.o,b,void 0);b.uj=2;b.Zg=m6(c.clone());(new window.Image).src=b.Zg;b.ck=(0,g.F)();M6(b)}SCa(a)},UCa=function(a){a.qI(1,0);
a.En=W6(a,null,a.Er);a7(a)},RCa=function(a){a.Og&&(a.Og.abort(),a.Og=null);
a.wc&&(a.wc.cancel(),a.wc=null);a.ng&&(g.w.clearTimeout(a.ng),a.ng=null);b7(a);a.Ud&&(a.Ud.cancel(),a.Ud=null);a.Qg&&(g.w.clearTimeout(a.Qg),a.Qg=null)},VCa=function(a,b){if(0==a.g)throw Error("Invalid operation: sending map when state is closed");
a.l.push(new NCa(a.cP++,b));2!=a.g&&3!=a.g||a7(a)},a7=function(a){a.Ud||a.Qg||(a.Qg=T6((0,g.z)(a.sC,a),0),a.hj=0)},XCa=function(a,b){if(1==a.g){if(!b){a.Jl=Math.floor(1E5*Math.random());
var c=a.Jl++,d=new K6(a,"",c,void 0);d.bi=null;var e=c7(a),f=a.En.clone();g.Fm(f,"RID",c);g.Fm(f,"CVER","1");$6(a,f);CCa(d,f,e);a.Ud=d;a.g=2}}else 3==a.g&&(b?WCa(a,b):0==a.l.length||a.Ud||WCa(a))},WCa=function(a,b){if(b)if(6<a.Ph){a.l=a.A.concat(a.l);
a.A.length=0;var c=a.Jl-1;var d=c7(a)}else c=b.D,d=b.Ai;else c=a.Jl++,d=c7(a);var e=a.En.clone();g.Fm(e,"SID",a.o);g.Fm(e,"RID",c);g.Fm(e,"AID",a.Ij);$6(a,e);c=new K6(a,a.o,c,a.hj+1);c.bi=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.Ud=c;CCa(c,e,d)},$6=function(a,b){if(a.qd){var c=a.qd.hy();
c&&g.Ib(c,function(a,c){g.Fm(b,c,a)})}},c7=function(a){var b=Math.min(a.l.length,1E3),c=["count="+b];
if(6<a.Ph&&0<b){var d=a.l[0].g;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.l[e].g,k=a.l[e].map;f=6>=a.Ph?e:f-d;try{g.Ib(k,function(a,b){c.push("req"+f+"_"+b+"="+(0,window.encodeURIComponent)(a))})}catch(l){c.push("req"+f+"_type="+(0,window.encodeURIComponent)("_badmap"))}}a.A=a.A.concat(a.l.splice(0,b));
return c.join("&")},YCa=function(a){a.wc||a.ng||(a.D=1,a.ng=T6((0,g.z)(a.rC,a),0),a.Si=0)},d7=function(a){if(a.wc||a.ng||3<=a.Si)return!1;
a.D++;a.ng=T6((0,g.z)(a.rC,a),ZCa(a,a.Si));a.Si++;return!0},X6=function(a,b,c){a.Mp=c;
a.Jf=b.tg;a.C||UCa(a)},b7=function(a){null!=a.Rh&&(g.w.clearTimeout(a.Rh),a.Rh=null)},ZCa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},e7=function(a,b){if(2==b||9==b){var c=null;
a.qd&&(c=null);var d=(0,g.z)(a.aV,a);c||(c=new g.wm("//www.google.com/images/cleardot.gif"),m6(c));JCa(c.toString(),1E4,d)}else O6(2);$Ca(a,b)},$Ca=function(a,b){a.g=0;
a.qd&&a.qd.Zw(b);SCa(a);RCa(a)},SCa=function(a){a.g=0;
a.Jf=-1;if(a.qd)if(0==a.A.length&&0==a.l.length)a.qd.Oq();else{g.Wa(a.A);var b=g.Wa(a.l);a.A.length=0;a.l.length=0;a.qd.Oq(b)}},W6=function(a,b,c){var d=g.Gm(c);
if(""!=d.l)b&&g.ym(d,b+"."+d.l),g.zm(d,d.B);else{var e=window.location;d=$Ba(e.protocol,b?b+"."+e.hostname:e.hostname,e.port,c)}a.Nk&&g.Ib(a.Nk,function(a,b){g.Fm(d,b,a)});
g.Fm(d,"VER",a.Ph);$6(a,d);return d},T6=function(a,b){if(!g.Aa(a))throw Error("Fn must not be null and must be a function");
return g.w.setTimeout(function(){a()},b)},O6=function(a){f7.dispatchEvent(new OCa(f7,a))},aDa=function(){},bDa=function(a,b){this.action=a;
this.params=b||{}},g7=function(a,b){g.K.call(this);
this.g=new g.Zt(this.eT,0,this);g.M(this,this.g);this.ed=5E3;this.l=0;if(g.Aa(a))b&&(a=(0,g.z)(a,b));else if(a&&g.Aa(a.handleEvent))a=(0,g.z)(a.handleEvent,a);else throw Error("Invalid listener argument");this.o=a},h7=function(a,b,c){this.K=a;
this.C=b;this.o=new g.ZC;this.l=new g7(this.GV,this);this.g=this.Wa=null;this.I=!1;this.B=null;this.H="";this.F=this.A=0;this.D=[];this.L=c||!1},cDa=function(a){return{firstTestResults:[""],
secondTestResults:!a.g.Mp,sessionId:a.g.o,arrayId:a.g.Ij}},dDa=function(a,b){a.F=b||0;
a.l.stop();a.g&&(3==a.g.g&&XCa(a.g),TCa(a.g));a.F=0},i7=function(a){return!!a.g&&3==a.g.g},eDa=function(a,b){(a.C.loungeIdToken=b)||a.l.stop()},j7=function(a){this.port=this.domain="";
this.g="/api/lounge";this.l=!0;a=a||window.document.location.href;var b=g.Jg(a)||"";b&&(this.port=":"+b);this.domain=g.Ig(a)||"";a=g.Fb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.yb(a,"10.0")&&(this.l=!1))},k7=function(a,b){var c=a.g;
if(g.t(void 0)?0:a.l)c="https://"+a.domain+a.port+a.g;return g.Tg(c+b,{})},l7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Ea(a.A,d,!0),onError:g.Ea(a.o,e),wd:g.Ea(a.B,e)};c&&(a.Kb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.oE(b,a)},iDa=function(){var a=fDa;
gDa();m7.push(a);hDa(m7)},n7=function(a,b){gDa();
var c=m7,d=jDa(a,String(b));g.Pa(c)?kDa(d):(hDa(c),(0,g.B)(c,function(a){a(d)}))},gDa=function(){m7||(m7=g.x("yt.mdx.remote.debug.handlers_")||[],g.va("yt.mdx.remote.debug.handlers_",m7,void 0))},kDa=function(a){var b=(o7+1)%50;
o7=b;p7[b]=a;q7||(q7=49==b)},hDa=function(a){var b=p7;
if(b[0]){var c=o7,d=q7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.B)(a,function(a){a(e)})}while(d!=c);
p7=Array(50);o7=-1;q7=!1}},jDa=function(a,b){var c=((0,g.F)()-lDa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},r7=function(a){g.RF.call(this);
this.D=a;this.g=[]},mDa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.g.push(b);return!0},nDa=function(a,b){var c=a.g.length!=b.length;
a.g=(0,g.Kd)(a.g,function(a){return!!u6(b,a)});
for(var d=0,e=b.length;d<e;d++)c=mDa(a,b[d])||c;return c},oDa=function(a,b){var c=a.g.length;
a.g=(0,g.Kd)(a.g,function(a){return!(a||b?!a!=!b?0:a.id==b.id:1)});
return a.g.length<c},s7=function(a,b,c,d){g.RF.call(this);
this.C=a;this.B=b;this.o=c;this.A=d;this.l=0;this.g=null;this.ya=window.NaN},u7=function(a){r7.call(this,"LocalScreenService");
this.o=a;this.l=window.NaN;t7(this);this.info("Initializing with "+s6(this.g))},pDa=function(a){if(a.g.length){var b=(0,g.G)(a.g,function(a){return a.id}),c=k7(a.o,"/pairing/get_lounge_token_batch");
l7(a.o,c,{screen_ids:b.join(",")},(0,g.z)(a.YI,a),(0,g.z)(a.XI,a))}},t7=function(a){var b=hCa(nCa());
b=(0,g.Kd)(b,function(a){return!a.uuid});
return nDa(a,b)},v7=function(a,b){pCa((0,g.G)(a.g,fCa));
b&&oCa()},x7=function(a,b){g.RF.call(this);
this.C=b;var c=g.YG("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.C(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.Oa(c,l)}this.g=d;this.B=a;this.o=this.A=window.NaN;this.l=null;w7("Initialized with "+g.Ag(this.g))},qDa=function(a,b,c){var d=k7(a.B,"/pairing/get_screen_availability");
l7(a.B,d,{lounge_token:b.token},(0,g.z)(function(a){a=a.screens||[];for(var d=0,e=a.length;d<e;++d)if(a[d].loungeToken==b.token){c("online"==a[d].status);return}c(!1)},a),(0,g.z)(function(){c(!1)},a))},y7=function(a,b){a:if(g.Mb(b)!=g.Mb(a.g))var c=!1;
else{c=g.Qb(b);for(var d=0,e=c.length;d<e;++d)if(!a.g[c[d]]){c=!1;break a}c=!0}c||(w7("Updated online screens: "+g.Ag(a.g)),a.g=b,a.R("screenChange"));rDa(a)},z7=function(a){(0,window.isNaN)(a.o)||g.aE(a.o);
a.o=g.ZD((0,g.z)(a.Fu,a),0<a.A&&a.A<(0,g.F)()?2E4:1E4)},w7=function(a){n7("OnlineScreenService",a)},sDa=function(a){var b={};
(0,g.B)(a.C(),function(a){a.token?b[a.token]=a.id:this.fc("Requesting availability of screen w/o lounge token.")});
return b},rDa=function(a){a=g.Qb(g.Jb(a.g,function(a){return a}));
g.fb(a);a.length?g.XG("yt-remote-online-screen-ids",a.join(","),60):g.ZG("yt-remote-online-screen-ids")},A7=function(a){r7.call(this,"ScreenService");
this.C=a;this.l=this.o=null;this.A=[];this.B={};tDa(this)},vDa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.B[b]);var k=a.ie();if(k=(c?v6(k,c):null)||v6(k,b)){k.uuid=b;var l=B7(a,k);qDa(a.l,l,function(a){e(a?l:null)})}else c?uDa(a,c,(0,g.z)(function(a){var f=B7(this,new p6({name:d,
screenId:c,loungeToken:a,dialId:b||""}));qDa(this.l,f,function(a){e(a?f:null)})},a),f):e(null)},wDa=function(a,b){for(var c=0,d=a.g.length;c<d;++c)if(a.g[c].name==b)return a.g[c];
return null},uDa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={Kb:{screen_ids:b},method:"POST",context:a,onSuccess:function(a,e){var f=e&&e.screens||[];f[0]&&f[0].screenId==b?c(f[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.oE(k7(a.C,"/pairing/get_lounge_token_batch"),e)},xDa=function(a){a.g=a.o.ie();
var b=a.B,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.g.length;b<d;++b){var e=a.g[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+s6(a.g))},tDa=function(a){C7(a);
a.o=new u7(a.C);a.o.subscribe("screenChange",(0,g.z)(a.oJ,a));xDa(a);a.A=hCa(g.YG("yt-remote-automatic-screen-cache")||[]);C7(a);a.info("Initializing automatic screens: "+s6(a.A));a.l=new x7(a.C,(0,g.z)(a.ie,a,!0));a.l.subscribe("screenChange",(0,g.z)(function(){this.R("onlineScreenChange")},a))},B7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=v6(a.A,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.A.push(b),g.XG("yt-remote-automatic-screen-cache",(0,g.G)(a.A,fCa)));C7(a);a.B[b.uuid]=b.id;g.XG("yt-remote-device-id-map",a.B,31536E3);return b},C7=function(a){a.B=g.YG("yt-remote-device-id-map")||{}},D7=function(a,b,c){g.RF.call(this);
this.L=c;this.H=a;this.l=b;this.o=null},E7=function(a,b){n7(a.L,b)},F7=function(a,b){D7.call(this,a,b,"CastSession");
this.g=null;this.A=0;this.C=(0,g.z)(this.MV,this);this.B=(0,g.z)(this.QT,this);this.A=g.ZD((0,g.z)(function(){yDa(this,null)},this),12E4)},zDa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Ag(void 0));
var b={type:"getMdxSessionStatus"};a.g?a.g.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.y,(0,g.z)(function(){E7(this,"Failed to send message: getMdxSessionStatus.")},a)):E7(a,"Sending yt message without session: "+g.Ag(b))},yDa=function(a,b){g.aE(a.A);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.o||a.o.id!=b){var c=(0,g.z)(a.Ko,a),d=(0,g.z)(a.oe,a);a.vy(b,c,d,5)}}else a.oe(Error("Waiting for session status timed out."))},G7=function(a,b,c){D7.call(this,a,b,"DialSession");
this.A=this.F=null;this.I="";this.N=c;this.B=null;this.D=g.y;this.C=window.NaN;this.K=(0,g.z)(this.PV,this);this.g=g.y},ADa=function(a){a.g=a.H.DE(a.I,a.l.label,a.l.friendlyName,(0,g.z)(function(a){this.g=g.y;
this.Ko(a)},a),(0,g.z)(function(a){this.g=g.y;
this.oe(a)},a))},BDa=function(a){var b={};
b.pairingCode=a.I;b.theme=a.N;if(a.B){var c=a.B.currentTime||0;b.v=a.B.videoId;b.t=c}rCa()&&(b.env_useStageMdx=1);return g.Rg(b)},H7=function(a,b){D7.call(this,a,b,"ManualSession");
this.g=g.ZD((0,g.z)(this.Kj,this,null),150)},I7=function(a,b,c,d){g.RF.call(this);
this.l=a;this.D=b||"233637DE";this.C=c||"cl";this.F=d||!1;this.g=null;this.B=!1;this.o=[];this.A=(0,g.z)(this.qS,this)},CDa=function(a,b){return b?g.Ja(a.o,function(a){return q6(b,a.label)},a):null},J7=function(a){n7("Controller",a)},fDa=function(a){window.chrome&&window.chrome.cast&&window.chrome.cast.logMessage&&window.chrome.cast.logMessage(a)},K7=function(a){return a.B||!!a.o.length||!!a.g},L7=function(a,b,c){b!=a.g&&(g.bf(a.g),(a.g=b)?(c?a.R("yt-remote-cast2-receiver-resumed",b.l):a.R("yt-remote-cast2-receiver-selected",
b.l),b.subscribe("sessionScreen",(0,g.z)(a.pC,a,b)),b.o?a.R("yt-remote-cast2-session-change",b.o):c&&a.g.Kj(null)):a.R("yt-remote-cast2-session-change",null))},DDa=function(a){var b=a.l.CE(),c=a.g&&a.g.l;
a=(0,g.G)(b,function(a){c&&q6(a,c.label)&&(c=null);var b=a.uuid?a.uuid:a.id,d=CDa(this,a);d?(d.label=b,d.friendlyName=a.name):(d=new window.chrome.cast.Receiver(b,a.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM);return d},a);
c&&(c.receiverType!=window.chrome.cast.ReceiverType.CUSTOM&&(c=new window.chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=window.chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},JDa=function(a,b,c,d,e,f,k){EDa()?FDa(b,e,f,k)&&(N7(!0),window.chrome&&window.chrome.cast&&window.chrome.cast.isAvailable?GDa(a,c):(window.__onGCastApiAvailable=function(b,d){b?GDa(a,c):(O7("Failed to load cast API: "+d),P7(!1),N7(!1),g.ZG("yt-remote-cast-available"),g.ZG("yt-remote-cast-receiver"),HDa(),
c(!1))},d?window.spf?window.spf.script.load("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js","",void 0):uCa():G6("CriOS")?zCa():G6("Android")&&G6("Chrome/")&&window.navigator.presentation?ACa():window.chrome&&window.navigator.presentation&&!G6("Edge")?(H6(),D6(IDa.map(xCa))):E6())):M7("Cannot initialize because not running Chrome")},HDa=function(){M7("dispose");
var a=Q7();a&&a.dispose();g.va("yt.mdx.remote.cloudview.instance_",null,void 0);KDa(!1);g.dG(R7);R7.length=0},S7=function(){return!!g.YG("yt-remote-cast-installed")},LDa=function(){var a=g.YG("yt-remote-cast-receiver");
return a?a.friendlyName:null},MDa=function(){M7("clearCurrentReceiver");
g.ZG("yt-remote-cast-receiver")},NDa=function(){return S7()?Q7()?Q7().getCastSession():(O7("getCastSelector: Cast is not initialized."),null):(O7("getCastSelector: Cast API is not installed!"),null)},U7=function(){S7()?Q7()?T7()?(M7("Requesting cast selector."),Q7().requestSession()):(M7("Wait for cast API to be ready to request the session."),R7.push(g.cG("yt-remote-cast2-api-ready",U7))):O7("requestCastSelector: Cast is not initialized."):O7("requestCastSelector: Cast API is not installed!")},V7=
function(a,b){T7()?Q7().setConnectedScreenStatus(a,b):O7("setConnectedScreenStatus called before ready.")},EDa=function(){var a=0<=g.Fb.search(/ (CrMo|Chrome|CriOS)\//);
return g.GI||a},ODa=function(a,b){Q7().init(a,b)},FDa=function(a,b,c,d){var e=!1;
Q7()||(a=new I7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(a){g.XG("yt-remote-cast-available",a);g.gG("yt-remote-cast2-availability-change",a)}),a.subscribe("yt-remote-cast2-receiver-selected",function(a){M7("onReceiverSelected: "+a.friendlyName);
g.XG("yt-remote-cast-receiver",a);g.gG("yt-remote-cast2-receiver-selected",a)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(a){M7("onReceiverResumed: "+a.friendlyName);
g.XG("yt-remote-cast-receiver",a)}),a.subscribe("yt-remote-cast2-session-change",function(a){M7("onSessionChange: "+r6(a));
a||g.ZG("yt-remote-cast-receiver");g.gG("yt-remote-cast2-session-change",a)}),g.va("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
M7("cloudview.createSingleton_: "+e);return e},Q7=function(){return g.x("yt.mdx.remote.cloudview.instance_")},GDa=function(a,b){P7(!0);
N7(!1);ODa(a,function(a){a?(KDa(!0),g.fG("yt-remote-cast2-api-ready")):(O7("Failed to initialize cast API."),P7(!1),g.ZG("yt-remote-cast-available"),g.ZG("yt-remote-cast-receiver"),HDa());b(a)})},M7=function(a){n7("cloudview",a)},O7=function(a){n7("cloudview",a)},P7=function(a){M7("setCastInstalled_ "+a);
g.XG("yt-remote-cast-installed",a)},T7=function(){return!!g.x("yt.mdx.remote.cloudview.apiReady_")},KDa=function(a){M7("setApiReady_ "+a);
g.va("yt.mdx.remote.cloudview.apiReady_",a,void 0)},N7=function(a){g.va("yt.mdx.remote.cloudview.initializing_",a,void 0)},W7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.g=-1;this.muted=!1;this.audioTrackId=null;this.D=this.F=0;this.l=null;this.hasNext=this.Mf=!1;this.I=this.H=this.o=this.B=0;this.A=window.NaN;this.C=!1;this.reset(a)},X7=function(a){a.audioTrackId=null;
a.l=null;a.g=-1;a.Mf=!1;a.hasNext=!1;a.F=0;a.D=(0,g.F)();a.B=0;a.o=0;a.H=0;a.I=0;a.A=window.NaN;a.C=!1},Y7=function(a){return a.jb()?((0,g.F)()-a.D)/1E3:0},Z7=function(a,b){a.F=b;
a.D=(0,g.F)()},$7=function(a){switch(a.g){case 1:case 1081:return((0,g.F)()-a.D)/1E3+a.F;
case -1E3:return 0}return a.F},a8=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&X7(a)},b8=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.g;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.cc(a.l);b.hasPrevious=a.Mf;b.hasNext=a.hasNext;b.playerTime=a.F;b.playerTimeAt=a.D;b.seekableStart=a.B;b.seekableEnd=a.o;b.duration=a.H;b.loadedTime=a.I;b.liveIngestionTime=a.A;return b},d8=function(a,b){g.RF.call(this);
this.g=0;this.A=a;this.C=[];this.B=new g.pC;this.o=this.l=null;this.H=(0,g.z)(this.MP,this);this.D=(0,g.z)(this.Ml,this);this.F=(0,g.z)(this.LP,this);this.I=(0,g.z)(this.YP,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Av,this),PDa(this))):c=3;0!=c&&(b?this.Av(c):g.ZD((0,g.z)(function(){this.Av(c)},this),0));
var d=NDa();d&&c8(this,d);this.subscribe("yt-remote-cast2-session-change",this.I)},e8=function(a){return new W7(a.A.getPlayerContextData())},PDa=function(a){(0,g.B)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.C.push(this.A.subscribe(a,g.Ea(this.lS,a),this))},a)},QDa=function(a){(0,g.B)(a.C,function(a){this.A.unsubscribeByKey(a)},a);
a.C.length=0},f8=function(a,b){50>a.B.Cc()&&g.rC(a.B,b)},h8=function(a,b,c){var d=e8(a);
Z7(d,c);-1E3!=d.g&&(d.g=b);g8(a,d)},i8=function(a,b,c){a.A.sendMessage(b,c)},g8=function(a,b){QDa(a);
a.A.setPlayerContextData(b8(b));PDa(a)},c8=function(a,b){a.o&&(a.o.removeUpdateListener(a.H),a.o.removeMediaListener(a.D),a.Ml(null));
a.o=b;a.o&&(n7("CP","Setting cast session: "+a.o.sessionId),a.o.addUpdateListener(a.H),a.o.addMediaListener(a.D),a.o.media.length&&a.Ml(a.o.media[0]))},RDa=function(a){var b=a.l.media,c=a.l.customData;
if(b&&c){var d=e8(a);b.contentId!=d.videoId&&n7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.g=c.playerState;Z7(d,a.l.getEstimatedTime());g8(a,d)}else n7("CP","No cast media video. Ignoring state update.")},j8=function(a,b,c){return(0,g.z)(function(a){this.fc("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=window.chrome.cast.ErrorCode.TIMEOUT&&(this.fc("Retrying "+b+" using MDx browser channel."),i8(this,b,c))},a)},k8=function(a,b,c){g.RF.call(this);
this.B=window.NaN;this.N=!1;this.I=this.H=this.K=this.L=window.NaN;this.U=[];this.A=this.D=this.o=this.Xa=this.g=null;this.pa=a;this.U.push(g.AF(window,"beforeunload",(0,g.z)(this.NI,this)));this.l=[];this.Xa=new W7;this.Z=b.id;this.g=SDa(this,c);this.g.subscribe("handlerOpened",this.QP,this);this.g.subscribe("handlerClosed",this.NP,this);this.g.subscribe("handlerError",this.OP,this);this.g.subscribe("handlerMessage",this.PP,this);eDa(this.g,b.token);this.subscribe("remoteQueueChange",function(){var a=
this.Xa.videoId;g.$G()&&g.XG("yt-remote-session-video-id",a)},this)},l8=function(a){n7("conn",a)},SDa=function(a,b){return new h7(k7(a.pa,"/bc"),b)},m8=function(a,b){a.R("proxyStateChange",b)},TDa=function(a){a.B=g.ZD((0,g.z)(function(){l8("Connecting timeout");
this.C(1)},a),2E4)},n8=function(a){g.aE(a.B);
a.B=window.NaN},o8=function(a){g.aE(a.L);
a.L=window.NaN},UDa=function(a){p8(a);
a.K=g.ZD((0,g.z)(function(){q8(this,"getNowPlaying")},a),2E4)},p8=function(a){g.aE(a.K);
a.K=window.NaN},WDa=function(a,b){b&&(n8(a),o8(a));
b==(i7(a.g)&&(0,window.isNaN)(a.B))?b&&(m8(a,1),q8(a,"getSubtitlesTrack")):b?(a.X()&&a.Xa.reset(),m8(a,1),q8(a,"getNowPlaying"),VDa(a)):a.C(1)},XDa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Xa.videoId&&(g.Xb(b.params)?a.Xa.l=null:a.Xa.l=b.params,a.R("remotePlayerChange"))},YDa=function(a,b){var c=b.params.videoId||b.params.video_id,d=(0,window.parseInt)(b.params.currentIndex,10);
a.Xa.listId=b.params.listId||a.Xa.listId;a8(a.Xa,c,d);a.R("remoteQueueChange")},$Da=function(a,b){b.params=b.params||{};
YDa(a,b);ZDa(a,b);a.R("autoplayDismissed")},ZDa=function(a,b){var c=(0,window.parseInt)(b.params.currentTime||b.params.current_time,10);
Z7(a.Xa,(0,window.isNaN)(c)?0:c);c=(0,window.parseInt)(b.params.state,10);c=(0,window.isNaN)(c)?-1:c;-1==c&&-1E3==a.Xa.g&&(c=-1E3);a.Xa.g=c;c=Number(b.params.loadedTime);a.Xa.I=(0,window.isNaN)(c)?0:c;c=Number(b.params.duration);a.Xa.H=(0,window.isNaN)(c)?0:c;c=a.Xa;var d=Number(b.params.liveIngestionTime);c.A=d;c.C=(0,window.isNaN)(d)?!1:!0;c=a.Xa;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.B=(0,window.isNaN)(d)?0:d;c.o=(0,window.isNaN)(e)?0:e;1==a.Xa.g?UDa(a):p8(a);
a.R("remotePlayerChange")},aEa=function(a,b){if(-1E3!=a.Xa.g){var c=1085;
switch((0,window.parseInt)(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Xa.g=c;c=(0,window.parseInt)(b.params.currentTime,10);Z7(a.Xa,(0,window.isNaN)(c)?0:c);a.R("remotePlayerChange")}},bEa=function(a,b){var c="true"==b.params.muted;
a.Xa.volume=(0,window.parseInt)(b.params.volume,10);a.Xa.muted=c;a.R("remotePlayerChange")},cEa=function(a,b){a.D=b.params.videoId;
a.R("nowAutoplaying",(0,window.parseInt)(b.params.timeout,10))},dEa=function(a,b){var c="true"==b.params.hasNext;
a.Xa.Mf="true"==b.params.hasPrevious;a.Xa.hasNext=c;a.R("previousNextChange")},VDa=function(a){g.aE(a.I);
a.I=g.ZD((0,g.z)(a.C,a,1),864E5)},q8=function(a,b,c){c?l8("Sending: action="+b+", params="+g.Ag(c)):l8("Sending: action="+b);
a.g.sendMessage(b,c)},r8=function(a){r7.call(this,"ScreenServiceProxy");
this.dd=a;this.l=[];this.l.push(this.dd.$_s("screenChange",(0,g.z)(this.KV,this)));this.l.push(this.dd.$_s("onlineScreenChange",(0,g.z)(this.MR,this)))},iEa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.TD("MDX_CONFIG")||b;jCa();z6();s8||(s8=new j7(b?b.loungeApiHost:void 0),rCa()&&(s8.g="/api/loungedev"));t8||(t8=g.x("yt.mdx.remote.deferredProxies_")||[],g.va("yt.mdx.remote.deferredProxies_",t8,void 0));eEa();var c=u8();if(!c){var d=new A7(s8);g.va("yt.mdx.remote.screenService_",d,void 0);c=u8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);JDa(a,d,function(a){a?v8()&&V7(v8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){g.gG("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.x("yt.mdx.remote.initialized_")&&(g.va("yt.mdx.remote.initialized_",!0,void 0),w8("Initializing: "+g.Ag(b)),x8.push(g.cG("yt-remote-cast2-availability-change",function(){g.gG("yt-remote-receiver-availability-change")})),x8.push(g.cG("yt-remote-cast2-receiver-selected",function(){y8(null);
g.gG("yt-remote-auto-connect","cast-selector-receiver")})),x8.push(g.cG("yt-remote-cast2-receiver-resumed",function(){g.gG("yt-remote-receiver-resumed","cast-selector-receiver")})),x8.push(g.cG("yt-remote-cast2-session-change",fEa)),x8.push(g.cG("yt-remote-connection-change",function(a){a?V7(v8(),"YouTube TV"):z8()||(V7(null,null),MDa())})),a=A8(),b.isAuto&&(a.id+="#dial"),g.XF("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),w8(" -- with channel params: "+
g.Ag(a)),gEa(a),c.start(),v8()||hEa())},kEa=function(){var a=jEa();
S7()&&g.YG("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},jEa=function(){var a=u8().dd.$_gos();
var b=B8();b&&C8()&&(u6(a,b)||a.push(b));return iCa(a)},D8=function(){var a=lEa();
!a&&S7()&&LDa()&&(a={key:"cast-selector-receiver",name:LDa()});return a},lEa=function(){var a=jEa(),b=B8();
b||(b=z8());return g.Ja(a,function(a){return b&&q6(b,a.key)?!0:!1})},B8=function(){var a=v8();
if(!a)return null;var b=u8().ie();return v6(b,a)},fEa=function(a){w8("remote.onCastSessionChange_: "+r6(a));
if(a){var b=B8();b&&b.id==a.id?V7(b.id,"YouTube TV"):(b&&E8(),F8(a,1))}else C8()&&E8()},E8=function(){T7()?Q7().stopSession():O7("stopSession called before API ready.");
var a=C8();a&&(a.disconnect(1),G8(null))},H8=function(){var a=C8();
return!!a&&3!=a.getProxyState()},w8=function(a){n7("remote",a)},u8=function(){if(!I8){var a=g.x("yt.mdx.remote.screenService_");
I8=a?new r8(a):null}return I8},v8=function(){return g.x("yt.mdx.remote.currentScreenId_")},mEa=function(a){g.va("yt.mdx.remote.currentScreenId_",a,void 0)},nEa=function(){return g.x("yt.mdx.remote.connectData_")},y8=function(a){g.va("yt.mdx.remote.connectData_",a,void 0)},C8=function(){return g.x("yt.mdx.remote.connection_")},G8=function(a){var b=C8();
y8(null);a||mEa("");g.va("yt.mdx.remote.connection_",a,void 0);t8&&((0,g.B)(t8,function(b){b(a)}),t8.length=0);
b&&!a?g.gG("yt-remote-connection-change",!1):!b&&a&&g.gG("yt-remote-connection-change",!0)},z8=function(){var a=g.$G();
if(!a)return null;var b=u8().ie();return v6(b,a)},F8=function(a,b){B8()&&B8();
mEa(a.id);var c=new k8(s8,a,A8());c.connect(b,nEa());c.subscribe("beforeDisconnect",function(a){g.gG("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){C8()&&G8(null)});
G8(c)},hEa=function(){var a=z8();
a?(w8("Resume connection to: "+r6(a)),F8(a,0)):(A6(),MDa(),w8("Skipping connecting because no session screen found."))},eEa=function(){var a=A8();
if(g.Xb(a)){a=y6();var b=g.YG("yt-remote-session-name")||"",c=g.YG("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.va("yt.mdx.remote.channelParams_",a,void 0)}},A8=function(){return g.x("yt.mdx.remote.channelParams_")||{}},gEa=function(a){a?(g.XG("yt-remote-session-app",a.app),g.XG("yt-remote-session-name",a.name)):(g.ZG("yt-remote-session-app"),g.ZG("yt-remote-session-name"));
g.va("yt.mdx.remote.channelParams_",a,void 0)},J8=function(a,b,c){g.K.call(this);
this.F=a;this.l=b;this.o=new g.OF(this);g.M(this,this.o);this.o.O(b,"onCaptionsTrackListChanged",this.fR);this.o.O(b,"captionschanged",this.KP);this.o.O(b,"captionssettingschanged",this.QD);this.o.O(b,"videoplayerreset",this.Lo);this.o.O(b,"mdxautoplaycancel",this.TH);this.U=this.o.O(b,"onVolumeChange",this.ZB);this.D=!1;this.g=c;c.subscribe("proxyStateChange",this.mC,this);c.subscribe("remotePlayerChange",this.Pl,this);c.subscribe("remoteQueueChange",this.Lo,this);c.subscribe("autoplayUpNext",this.JB,
this);c.subscribe("previousNextChange",this.jC,this);c.subscribe("nowAutoplaying",this.bC,this);c.subscribe("autoplayDismissed",this.IB,this);this.suggestion=null;this.H=new g.DP(64);this.A=new g.Zt(this.MD,500,this);g.M(this,this.A);this.B=new g.Zt(this.ND,1E3,this);g.M(this,this.B);this.K=new I6(this.nV,0,this);g.M(this,this.K);this.C={};this.L=new g.Zt(this.oE,1E3,this);g.M(this,this.L);this.I=new g.Uk(this.KN,1E3,this);g.M(this,this.I);this.N=g.y;this.QD();this.Lo();this.Pl()},K8=function(a,b){var c=
a.F,d=a.l.getVideoData().lengthSeconds;
c.H=b||0;c.g.R("progresssync",b,d)},oEa=function(a){K8(a,0);
a.A.stop();L8(a,new g.DP(64))},N8=function(a,b){if(M8(a)&&!a.D){var c=null;
b&&(c={style:a.l.ri()},g.ec(c,b));a.g.BD(a.l.getVideoData(1).videoId,c);a.C=e8(a.g).l}},O8=function(a,b){var c=a.l.Wf();
if(c){var d=c.fe();var e=c.listId.toString()}var f=a.l.getVideoData(1);c=a.g;var k=f.videoId,l=d;d=f.playerParams;var m=f.Ej;f=ZBa(f);var n=e8(c);l=l||0;var q={videoId:k,currentIndex:l};a8(n,k,l);g.t(b)&&(Z7(n,b),q.currentTime=b);g.t(e)&&(q.listId=e);null!=d&&(q.playerParams=d);null!=m&&(q.clickTrackingParams=m);null!=f&&(q.locationInfo=g.Ag(f));i8(c,"setPlaylist",q);e||g8(c,n);L8(a,new g.DP(1))},pEa=function(a,b){if(b){var c=a.l.xc("captions","tracklist",{nz:1});
c&&c.length?(a.l.Jd("captions","track",b),a.D=!1):(a.l.Nj("captions"),a.D=!0)}else a.l.Jd("captions","track",{})},M8=function(a){return e8(a.g).videoId==a.l.getVideoData(1).videoId},L8=function(a,b){a.B.stop();
var c=a.H;if(!g.LP(c,b)){var d=g.V(b,2);d!=g.V(a.H,2)&&g.KU(a.l,d);a.H=b;qEa(a.F,c,b)}},P8=function(a){g.U.call(this,{G:"div",
M:"ytp-remote",J:[{G:"div",M:"ytp-remote-display-status",J:[{G:"div",M:"ytp-remote-display-status-icon",J:[g.Dpa()]},{G:"div",M:"ytp-remote-display-status-text",J:["{{statustext}}"]}]}]});this.o=new g.zV(this,250);g.M(this,this.o);this.A=a;this.O(a,"presentingplayerstatechange",this.B);rEa(this,g.HU(a))},rEa=function(a,b){if(3==a.A.Sa()){var c={RECEIVER_NAME:a.A.xc("remote","currentReceiver").name};
c=g.V(b,128)?g.T("YTP_MDX_STATUS_ERROR_2",c):b.jb()||g.V(b,4)?g.T("YTP_MDX_STATUS_PLAYING_2",c):g.T("YTP_MDX_STATUS_CONNECTED_2",c);a.updateValue("statustext",c);a.o.show()}else a.o.hide()},Q8=function(a,b){g.JZ.call(this,g.T("YTP_MDX_TITLE"),0,a,b);
this.o=a;this.H={};this.O(a,"onMdxReceiversChange",this.K);this.O(a,"presentingplayerstatechange",this.K);this.K()},R8=function(a){g.eV.call(this,a);
g.bH({YTP_MDX_CAST_SELECTOR:"Caster sur\u2026",YTP_MDX_MY_COMPUTER:"Cet ordinateur",YTP_MDX_PLAYER_ERROR:"Cette vid\u00e9o ne peut pas \u00eatre visionn\u00e9e \u00e0 distance.",YTP_MDX_STATUS_CONNECTED_2:"Connect\u00e9 \u00e0 $RECEIVER_NAME",YTP_MDX_STATUS_ERROR_2:"Erreur sur $RECEIVER_NAME",YTP_MDX_STATUS_PLAYING_2:"Lecture sur $RECEIVER_NAME",YTP_MDX_TITLE:"Lire sur"});this.o={key:t6(),name:g.T("YTP_MDX_MY_COMPUTER")};this.B=null;this.C=[];this.I=this.l=null;this.F=[this.o];this.A=this.o;this.D=
new g.DP(64);this.H=0;if(!g.WM(g.W(this.g))){a=this.g;var b=g.OH(a);b&&(b=b.so())&&(b=new Q8(a,b),g.M(this,b));b=new P8(a);g.M(this,b);g.ZU(a,b.element,4)}},qEa=function(a,b,c){a.D=c;
a.g.R("presentingplayerstatechange",new g.RP(c,b))},S8=function(a,b){if(b.key!=a.A.key)if(b.key==a.o.key)E8();
else{a.A=b;var c=a.g.getPlaylistId();var d=a.g.getVideoData(1);var e=d.videoId;if(c||e){var f=a.g.Wf();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.Yb(l).videoId}else k=[e];f=a.g.getCurrentTime(1);c={videoIds:k,listId:c,videoId:e,playerParams:d.playerParams,clickTrackingParams:d.Ej,index:Math.max(a.g.pA(),0),currentTime:0==f?void 0:f};(d=ZBa(d))&&(c.locationInfo=d);d=c}else d=null;w8("Connecting to: "+g.Ag(b));"cast-selector-receiver"==b.key?(y8(d||null),T7()?Q7().setLaunchParams(d||null):
O7("setLaunchParams called before ready.")):!d&&H8()&&v8()==b.key?g.gG("yt-remote-connection-change",!0):(E8(),y8(d||null),d=u8().ie(),(d=v6(d,b.key))&&F8(d,1))}},GCa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},S6={"'":"\\'"},sEa={},eCa={bX:"atp",v1:"ska",K0:"que",Y_:"mus",q1:"sus",jZ:"dsp"};
o6.prototype.kn=function(){var a=new o6({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.o=this.o;a.l=this.l;a.g=this.g};
var B6,x6="",F6=C6("loadGamesSDK")?"/cast_game_sender.js":"/cast_sender.js",yCa=C6("loadCastFramework")||C6("loadCastApplicationFramework"),IDa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.A(I6,g.K);g.h=I6.prototype;g.h.II=function(a){this.A=arguments;this.g=!1;this.ya?this.o=(0,g.F)()+this.ed:this.ya=g.ug(this.B,this.ed)};
g.h.stop=function(){this.ya&&(g.vg(this.ya),this.ya=null);this.o=null;this.g=!1;this.A=[]};
g.h.pause=function(){++this.l};
g.h.resume=function(){this.l&&(--this.l,!this.l&&this.g&&(this.g=!1,this.C.apply(null,this.A)))};
g.h.V=function(){this.stop();I6.aa.V.call(this)};
g.h.JI=function(){this.o?(this.ya=g.ug(this.B,this.o-(0,g.F)()),this.o=null):(this.ya=null,this.l?this.g=!0:(this.g=!1,this.C.apply(null,this.A)))};J6.prototype.stringify=function(a){return g.w.JSON.stringify(a,void 0)};
J6.prototype.parse=function(a){return g.w.JSON.parse(a,void 0)};g.h=K6.prototype;g.h.bi=null;g.h.wf=!1;g.h.wk=null;g.h.rv=null;g.h.ck=null;g.h.uj=null;g.h.Zg=null;g.h.yh=null;g.h.Ai=null;g.h.Qc=null;g.h.hm=0;g.h.xf=null;g.h.Np=null;g.h.ah=null;g.h.bl=-1;g.h.iD=!0;g.h.Nh=!1;g.h.Ir=0;g.h.Yo=null;var ECa={},N6={};g.h=K6.prototype;g.h.setTimeout=function(a){this.A=a};
g.h.hU=function(a){a=a.target;var b=this.Yo;b&&3==g.jx(a)?b.sj():this.wE(a)};
g.h.wE=function(a){try{if(a==this.Qc)a:{var b=g.jx(this.Qc),c=this.Qc.l,d=this.Qc.getStatus();if(g.xd&&!g.rc(10)||g.zd&&!g.qc("420+")){if(4>b)break a}else if(3>b||3==b&&!g.ff&&!g.px(this.Qc))break a;this.Nh||4!=b||7==c||(8==c||0>=d?this.g.qf(3):this.g.qf(2));U6(this);var e=this.Qc.getStatus();this.bl=e;var f=g.px(this.Qc);(this.wf=200==e)?(4==b&&Q6(this),this.B?(FCa(this,b,f),g.ff&&this.wf&&3==b&&(this.W.T(this.l,"tick",this.dU),this.l.start())):P6(this,f),this.wf&&!this.Nh&&(4==b?this.g.Jo(this):
(this.wf=!1,M6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.ah=3,O6(13)):(this.ah=0,O6(14)),Q6(this),R6(this))}}catch(k){this.Qc&&g.px(this.Qc)}finally{}};
g.h.dU=function(){var a=g.jx(this.Qc),b=g.px(this.Qc);this.hm<b.length&&(U6(this),FCa(this,a,b),this.wf&&4!=a&&M6(this))};
g.h.nT=function(a){T6((0,g.z)(this.mT,this,a),0)};
g.h.mT=function(a){this.Nh||(U6(this),P6(this,a),M6(this))};
g.h.uC=function(a){T6((0,g.z)(this.lT,this,a),0)};
g.h.lT=function(a){this.Nh||(Q6(this),this.wf=a,this.g.Jo(this),this.g.qf(4))};
g.h.cancel=function(){this.Nh=!0;Q6(this)};
g.h.DT=function(){this.wk=null;var a=(0,g.F)();0<=a-this.rv?(2!=this.uj&&this.g.qf(3),Q6(this),this.ah=2,O6(18),R6(this)):ICa(this,this.rv-a)};g.h=LCa.prototype;g.h.Gr=null;g.h.pe=null;g.h.Zo=!1;g.h.Ey=null;g.h.An=null;g.h.Ms=null;g.h.Hr=null;g.h.Le=null;g.h.tg=-1;g.h.al=null;g.h.Ck=null;g.h.connect=function(a){this.Hr=a;a=W6(this.g,null,this.Hr);O6(3);this.Ey=(0,g.F)();var b=this.g.F;null!=b?(this.al=b[0],(this.Ck=b[1])?(this.Le=1,MCa(this)):(this.Le=2,Y6(this))):(n6(a,"MODE","init"),this.pe=new K6(this,void 0,void 0,void 0),this.pe.bi=this.Gr,L6(this.pe,a,!1,null,!0),this.Le=0)};
g.h.UH=function(a){if(a)this.Le=2,Y6(this);else{O6(4);var b=this.g;b.Jf=b.Og.tg;e7(b,9)}a&&this.qf(2)};
g.h.ar=function(a){return this.g.ar(a)};
g.h.abort=function(){this.pe&&(this.pe.cancel(),this.pe=null);this.tg=-1};
g.h.Dy=function(){return!1};
g.h.nC=function(a,b){this.tg=a.bl;if(0==this.Le)if(b){try{var c=this.l.parse(b)}catch(d){c=this.g;c.Jf=this.tg;e7(c,2);return}this.al=c[0];this.Ck=c[1]}else c=this.g,c.Jf=this.tg,e7(c,2);else if(2==this.Le)if(this.Zo)O6(7),this.Ms=(0,g.F)();else if("11111"==b){if(O6(6),this.Zo=!0,this.An=(0,g.F)(),c=this.An-this.Ey,!g.xd||g.rc(10)||500>c)this.tg=200,this.pe.cancel(),O6(12),X6(this.g,this,!0)}else O6(8),this.An=this.Ms=(0,g.F)(),this.Zo=!1};
g.h.Jo=function(){this.tg=this.pe.bl;if(this.pe.wf)0==this.Le?this.Ck?(this.Le=1,MCa(this)):(this.Le=2,Y6(this)):2==this.Le&&((!g.xd||g.rc(10)?!this.Zo:200>this.Ms-this.An)?(O6(11),X6(this.g,this,!1)):(O6(12),X6(this.g,this,!0)));else{0==this.Le?O6(9):2==this.Le&&O6(10);var a=this.g;a.Jf=this.tg;e7(a,2)}};
g.h.Xl=function(){return this.g.Xl()};
g.h.isActive=function(){return this.g.isActive()};
g.h.qf=function(a){this.g.qf(a)};g.h=Z6.prototype;g.h.Nk=null;g.h.Ud=null;g.h.wc=null;g.h.Er=null;g.h.En=null;g.h.Rw=null;g.h.Pn=null;g.h.Jl=0;g.h.cP=0;g.h.qd=null;g.h.Qg=null;g.h.ng=null;g.h.Rh=null;g.h.Og=null;g.h.Mp=null;g.h.Ij=-1;g.h.Ez=-1;g.h.Jf=-1;g.h.hj=0;g.h.Si=0;g.h.Ph=8;var f7=new g.Ff;g.A(OCa,g.df);g.A(PCa,g.df);g.A(QCa,g.df);g.h=Z6.prototype;g.h.connect=function(a,b,c,d,e){O6(0);this.Er=b;this.Nk=c||{};d&&g.t(e)&&(this.Nk.OSID=d,this.Nk.OAID=e);this.C?(T6((0,g.z)(this.rx,this,a),100),UCa(this)):this.rx(a)};
g.h.rx=function(a){this.Og=new LCa(this);this.Og.Gr=null;this.Og.l=this.B;this.Og.connect(a)};
g.h.Dy=function(){return 0==this.g};
g.h.sC=function(a){this.Qg=null;XCa(this,a)};
g.h.rC=function(){this.ng=null;this.wc=new K6(this,this.o,"rpc",this.D);this.wc.bi=null;this.wc.Ir=0;var a=this.Rw.clone();g.Fm(a,"RID","rpc");g.Fm(a,"SID",this.o);g.Fm(a,"CI",this.Mp?"0":"1");g.Fm(a,"AID",this.Ij);$6(this,a);if(!g.xd||g.rc(10))g.Fm(a,"TYPE","xmlhttp"),L6(this.wc,a,!0,this.Pn,!1);else{g.Fm(a,"TYPE","html");var b=this.wc,c=!!this.Pn;b.uj=3;b.Zg=m6(a.clone());HCa(b,c)}};
g.h.nC=function(a,b){if(0!=this.g&&(this.wc==a||this.Ud==a))if(this.Jf=a.bl,this.Ud==a&&3==this.g)if(7<this.Ph){try{var c=this.B.parse(b)}catch(f){c=null}if(g.ya(c)&&3==c.length)if(0==c[0])a:{if(!this.ng){if(this.wc)if(this.wc.ck+3E3<this.Ud.ck)b7(this),this.wc.cancel(),this.wc=null;else break a;d7(this);O6(19)}}else this.Ez=c[1],0<this.Ez-this.Ij&&37500>c[2]&&this.Mp&&0==this.Si&&!this.Rh&&(this.Rh=T6((0,g.z)(this.FP,this),6E3));else e7(this,11)}else b!=sEa.eY.g&&e7(this,11);else if(this.wc==a&&
b7(this),!g.D(b)){c=this.B.parse(b);g.ya(c);for(var d=0;d<c.length;d++){var e=c[d];this.Ij=e[0];e=e[1];2==this.g?"c"==e[0]?(this.o=e[1],this.Pn=e[2],e=e[3],null!=e?this.Ph=e:this.Ph=6,this.g=3,this.qd&&this.qd.bx(),this.Rw=W6(this,this.Xl()?this.Pn:null,this.Er),YCa(this)):"stop"==e[0]&&e7(this,7):3==this.g&&("stop"==e[0]?e7(this,7):"noop"!=e[0]&&this.qd&&this.qd.ax(e),this.Si=0)}}};
g.h.FP=function(){null!=this.Rh&&(this.Rh=null,this.wc.cancel(),this.wc=null,d7(this),O6(20))};
g.h.Jo=function(a){if(this.wc==a){b7(this);this.wc=null;var b=2}else if(this.Ud==a)this.Ud=null,b=1;else return;this.Jf=a.bl;if(0!=this.g)if(a.wf)1==b?(b=(0,g.F)()-a.ck,f7.dispatchEvent(new PCa(f7,a.Ai?a.Ai.length:0,b,this.hj)),a7(this),this.A.length=0):YCa(this);else{var c=a.ah,d;if(!(d=3==c||7==c||0==c&&0<this.Jf)){if(d=1==b)this.Ud||this.Qg||1==this.g||2<=this.hj?d=!1:(this.Qg=T6((0,g.z)(this.sC,this,a),ZCa(this,this.hj)),this.hj++,d=!0);d=!(d||2==b&&d7(this))}if(d)switch(c){case 1:e7(this,5);
break;case 4:e7(this,10);break;case 3:e7(this,6);break;case 7:e7(this,12);break;default:e7(this,2)}}};
g.h.qI=function(a){if(!g.Oa(arguments,this.g))throw Error("Unexpected channel state: "+this.g);};
g.h.aV=function(a){a?O6(2):(O6(1),$Ca(this,8))};
g.h.ar=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new g.dx;a.F=!1;return a};
g.h.isActive=function(){return!!this.qd&&this.qd.isActive(this)};
g.h.qf=function(a){f7.dispatchEvent(new QCa(f7,a))};
g.h.Xl=function(){return!(!g.xd||g.rc(10))};
g.h=aDa.prototype;g.h.bx=function(){};
g.h.ax=function(){};
g.h.Zw=function(){};
g.h.Oq=function(){};
g.h.hy=function(){return{}};
g.h.isActive=function(){return!0};g.A(g7,g.K);g.h=g7.prototype;g.h.eT=function(){this.ed=Math.min(3E5,2*this.ed);this.o();this.l&&this.start()};
g.h.start=function(){var a=this.ed+15E3*Math.random();g.$t(this.g,a);this.l=(0,g.F)()+a};
g.h.stop=function(){this.g.stop();this.l=0};
g.h.isActive=function(){return this.g.isActive()};
g.h.reset=function(){this.g.stop();this.ed=5E3};g.A(h7,aDa);g.h=h7.prototype;g.h.subscribe=function(a,b,c){return this.o.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.o.unsubscribe(a,b,c)};
g.h.Md=function(a){return this.o.Md(a)};
g.h.R=function(a,b){return this.o.R.apply(this.o,arguments)};
g.h.dispose=function(){this.I||(this.I=!0,g.bf(this.o),dDa(this),g.bf(this.l),this.l=null)};
g.h.ia=function(){return this.I};
g.h.connect=function(a,b,c){if(!this.g||2!=this.g.g){this.H="";this.l.stop();this.B=a||null;this.A=b||0;a=this.K+"/test";b=this.K+"/bind";var d=new Z6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.L),e=this.g;e&&(e.qd=null);d.qd=this;this.g=d;e?this.g.connect(a,b,this.C,e.o,e.Ij):c?this.g.connect(a,b,this.C,c.sessionId,c.arrayId):this.g.connect(a,b,this.C)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.ec(c,b);this.l.isActive()||2==(this.g?this.g.g:0)?this.D.push(c):i7(this)&&VCa(this.g,c)};
g.h.bx=function(){this.l.reset();this.B=null;this.A=0;if(this.D.length){var a=this.D;this.D=[];for(var b=0,c=a.length;b<c;++b)VCa(this.g,a[b])}this.R("handlerOpened")};
g.h.Zw=function(a){var b=2==a&&401==this.g.Jf;4==a||b||this.l.start();this.R("handlerError",a)};
g.h.Oq=function(a){if(!this.l.isActive())this.R("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.D.push(d)}};
g.h.hy=function(){var a={v:2};this.H&&(a.gsessionid=this.H);0!=this.A&&(a.ui=""+this.A);0!=this.F&&(a.ui=""+this.F);this.B&&g.ec(a,this.B);return a};
g.h.ax=function(a){"S"==a[0]?this.H=a[1]:"gracefulReconnect"==a[0]?(this.l.start(),TCa(this.g)):this.R("handlerMessage",new bDa(a[0],a[1]))};
g.h.GV=function(){this.l.isActive();var a=this.g,b=0;a.wc&&b++;a.Ud&&b++;0!=b||this.connect(this.B,this.A)};j7.prototype.A=function(a,b,c,d){b?a(d):a({text:c.responseText})};
j7.prototype.o=function(a,b){a(Error("Request error: "+b.status))};
j7.prototype.B=function(a){a(Error("request timed out"))};var lDa=(0,g.F)(),m7=null,p7=Array(50),o7=-1,q7=!1;g.A(r7,g.RF);r7.prototype.ie=function(){return this.g};
r7.prototype.contains=function(a){return!!u6(this.g,a)};
r7.prototype.get=function(a){return a?v6(this.g,a):null};
r7.prototype.info=function(a){n7(this.D,a)};g.A(s7,g.RF);var tEa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.h=s7.prototype;g.h.start=function(){!this.g&&(0,window.isNaN)(this.ya)&&this.BE()};
g.h.stop=function(){this.g&&(this.g.abort(),this.g=null);(0,window.isNaN)(this.ya)||(g.aE(this.ya),this.ya=window.NaN)};
g.h.V=function(){this.stop();s7.aa.V.call(this)};
g.h.BE=function(){this.ya=window.NaN;this.g=g.oE(k7(this.C,"/pairing/get_screen"),{method:"POST",Kb:{pairing_code:this.B},timeout:5E3,onSuccess:(0,g.z)(this.IV,this),onError:(0,g.z)(this.HV,this),wd:(0,g.z)(this.JV,this)})};
g.h.IV=function(a,b){this.g=null;var c=b.screen||{};c.dialId=this.o;c.name=this.A;this.R("pairingComplete",new p6(c))};
g.h.HV=function(a){this.g=null;a.status&&404==a.status?this.l>=tEa.length?this.R("pairingFailed",Error("DIAL polling timed out")):(a=tEa[this.l],this.ya=g.ZD((0,g.z)(this.BE,this),a),this.l++):this.R("pairingFailed",Error("Server error "+a.status))};
g.h.JV=function(){this.g=null;this.R("pairingFailed",Error("Server not responding"))};g.A(u7,r7);g.h=u7.prototype;g.h.start=function(){t7(this)&&this.R("screenChange");!g.YG("yt-remote-lounge-token-expiration")&&pDa(this);g.aE(this.l);this.l=g.ZD((0,g.z)(this.start,this),1E4)};
g.h.add=function(a,b){t7(this);mDa(this,a);v7(this,!1);this.R("screenChange");b(a);a.token||pDa(this)};
g.h.remove=function(a,b){var c=t7(this);oDa(this,a)&&(v7(this,!1),c=!0);b(a);c&&this.R("screenChange")};
g.h.Hp=function(a,b,c,d){var e=t7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,v7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.R("screenChange")};
g.h.V=function(){g.aE(this.l);u7.aa.V.call(this)};
g.h.YI=function(a){t7(this);var b=this.g.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}v7(this,!b);b&&n7(this.D,"Missed "+b+" lounge tokens.")};
g.h.XI=function(a){n7(this.D,"Requesting lounge tokens failed: "+a)};g.A(x7,g.RF);g.h=x7.prototype;g.h.start=function(){var a=(0,window.parseInt)(g.YG("yt-remote-fast-check-period")||"0",10);(this.A=(0,g.F)()-144E5<a?0:a)?z7(this):(this.A=(0,g.F)()+3E5,g.XG("yt-remote-fast-check-period",this.A),this.Fu())};
g.h.isEmpty=function(){return g.Xb(this.g)};
g.h.update=function(){w7("Updating availability on schedule.");var a=this.C(),b=g.Jb(this.g,function(b,d){return b&&!!v6(a,d)},this);
y7(this,b)};
g.h.V=function(){g.aE(this.o);this.o=window.NaN;this.l&&(this.l.abort(),this.l=null);x7.aa.V.call(this)};
g.h.Fu=function(){g.aE(this.o);this.o=window.NaN;this.l&&this.l.abort();var a=sDa(this);if(g.Mb(a)){var b=k7(this.B,"/pairing/get_screen_availability");this.l=l7(this.B,b,{lounge_token:g.Qb(a).join(",")},(0,g.z)(this.KS,this,a),(0,g.z)(this.JS,this))}else y7(this,{}),z7(this)};
g.h.KS=function(a,b){this.l=null;var c=g.Qb(sDa(this));if(g.gb(c,g.Qb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;y7(this,d);z7(this)}else this.fc("Changing Screen set during request."),this.Fu()};
g.h.JS=function(a){this.fc("Screen availability failed: "+a);this.l=null;z7(this)};
g.h.fc=function(a){n7("OnlineScreenService",a)};g.A(A7,r7);g.h=A7.prototype;g.h.start=function(){this.o.start();this.l.start();this.g.length&&(this.R("screenChange"),this.l.isEmpty()||this.R("onlineScreenChange"))};
g.h.add=function(a,b,c){this.o.add(a,b,c)};
g.h.remove=function(a,b,c){this.o.remove(a,b,c);this.l.update()};
g.h.Hp=function(a,b,c,d){this.o.contains(a)?this.o.Hp(a,b,c,d):(a="Updating name of unknown screen: "+a.name,n7(this.D,a),d(Error(a)))};
g.h.ie=function(a){return a?this.g:g.Va(this.g,(0,g.Kd)(this.A,function(a){return!this.contains(a)},this))};
g.h.CE=function(){return(0,g.Kd)(this.ie(!0),function(a){return!!this.l.g[a.id]},this)};
g.h.DE=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new s7(this.C,a,b,c);f.subscribe("pairingComplete",(0,g.z)(function(a){g.bf(f);d(B7(this,a))},this));
f.subscribe("pairingFailed",function(a){g.bf(f);e(a)});
f.start();return(0,g.z)(f.stop,f)};
g.h.LV=function(a,b,c,d){g.oE(k7(this.C,"/pairing/get_screen"),{method:"POST",Kb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.z)(function(a,d){var e=new p6(d.screen||{});if(!e.name||wDa(this,e.name)){a:{var f=e.name;for(var m=2,n=b(f,m);wDa(this,n);){m++;if(20<m)break a;n=b(f,m)}f=n}e.name=f}c(B7(this,e))},this),
onError:(0,g.z)(function(a){d(Error("pairing request failed: "+a.status))},this),
wd:(0,g.z)(function(){d(Error("pairing request timed out."))},this)})};
g.h.V=function(){g.bf(this.o);g.bf(this.l);A7.aa.V.call(this)};
g.h.oJ=function(){xDa(this);this.R("screenChange");this.l.update()};
A7.prototype.dispose=A7.prototype.dispose;g.A(D7,g.RF);g.h=D7.prototype;g.h.Ko=function(a){this.o=a;this.R("sessionScreen",this.o)};
g.h.oe=function(a){this.ia()||(a&&E7(this,""+a),this.o=null,this.R("sessionScreen",null))};
g.h.info=function(a){n7(this.L,a)};
g.h.FE=function(){return null};
g.h.Lu=function(a){var b=this.l;a?(b.displayStatus=new window.chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;window.chrome.cast.setReceiverDisplayStatus(b,(0,g.z)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.z)(function(){E7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.V=function(){this.Lu("");D7.aa.V.call(this)};g.A(F7,D7);g.h=F7.prototype;g.h.Ku=function(a){if(this.g){if(this.g==a)return;E7(this,"Overriding cast sesison with new session object");this.g.removeUpdateListener(this.C);this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B)}this.g=a;this.g.addUpdateListener(this.C);this.g.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.B);zDa(this)};
g.h.Kj=function(a){this.info("launchWithParams no-op for Cast: "+g.Ag(a))};
g.h.stop=function(){this.g?this.g.stop((0,g.z)(function(){this.oe()},this),(0,g.z)(function(){this.oe(Error("Failed to stop receiver app."))},this)):this.oe(Error("Stopping cast device witout session."))};
g.h.Lu=g.y;g.h.V=function(){this.info("disposeInternal");g.aE(this.A);this.A=0;this.g&&(this.g.removeUpdateListener(this.C),this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B));this.g=null;F7.aa.V.call(this)};
g.h.QT=function(a,b){if(!this.ia())if(b){var c=g.Yw(b);if(g.Ba(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Ag(c));switch(d){case "mdxSessionStatus":yDa(this,c.screenId);break;default:E7(this,"Unknown youtube message: "+d)}}else E7(this,"Unable to parse message.")}else E7(this,"No data in message.")};
g.h.vy=function(a,b,c,d){vDa(this.H,this.l.label,a,this.l.friendlyName,(0,g.z)(function(e){e?b(e):0<=d?(E7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.ZD((0,g.z)(this.vy,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.FE=function(){return this.g};
g.h.MV=function(a){this.ia()||a||(E7(this,"Cast session died."),this.oe())};g.A(G7,D7);g.h=G7.prototype;g.h.Ku=function(a){this.A=a;this.A.addUpdateListener(this.K)};
g.h.Kj=function(a){this.B=a;this.D()};
g.h.stop=function(){this.g();this.g=g.y;g.aE(this.C);this.A?this.A.stop((0,g.z)(this.oe,this,null),(0,g.z)(this.oe,this,"Failed to stop DIAL device.")):this.oe()};
g.h.V=function(){this.g();this.g=g.y;g.aE(this.C);this.A&&this.A.removeUpdateListener(this.K);this.A=null;G7.aa.V.call(this)};
g.h.PV=function(a){this.ia()||a||(E7(this,"DIAL session died."),this.g(),this.g=g.y,this.oe())};
g.h.xs=function(a){this.I=t6();if(this.B){var b=new window.chrome.cast.DialLaunchResponse(!0,BDa(this));a(b);ADa(this)}else this.D=(0,g.z)(function(){g.aE(this.C);this.D=g.y;this.C=window.NaN;var b=new window.chrome.cast.DialLaunchResponse(!0,BDa(this));a(b);ADa(this)},this),this.C=g.ZD((0,g.z)(function(){this.D()},this),100)};
g.h.CK=function(a,b,c){vDa(this.H,this.F.receiver.label,a,this.l.friendlyName,(0,g.z)(function(a){a&&a.token?(this.Ko(a),b(new window.chrome.cast.DialLaunchResponse(!1))):this.xs(b,c)},this),(0,g.z)(function(a){E7(this,"Failed to get DIAL screen: "+a);
this.xs(b,c)},this))};g.A(H7,D7);H7.prototype.stop=function(){this.oe()};
H7.prototype.Ku=g.y;H7.prototype.Kj=function(){g.aE(this.g);this.g=window.NaN;var a=v6(this.H.ie(),this.l.label);a?this.Ko(a):this.oe(Error("No such screen"))};
H7.prototype.V=function(){g.aE(this.g);this.g=window.NaN;H7.aa.V.call(this)};g.A(I7,g.RF);g.h=I7.prototype;
g.h.init=function(a,b){window.chrome.cast.timeout.requestSession=3E4;var c=new window.chrome.cast.SessionRequest(this.D);this.F||(c.dialRequest=new window.chrome.cast.DialRequest("YouTube"));var d=window.chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?window.chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:window.chrome.cast.DefaultActionPolicy.CREATE_SESSION;c=new window.chrome.cast.ApiConfig(c,(0,g.z)(this.oC,this),(0,g.z)(this.uS,this),d,e);c.customDialLaunchCallback=(0,g.z)(this.pQ,this);window.chrome.cast.initialize(c,
(0,g.z)(function(){this.ia()||(window.chrome.cast.addReceiverActionListener(this.A),iDa(),this.l.subscribe("onlineScreenChange",(0,g.z)(this.EE,this)),this.o=DDa(this),window.chrome.cast.setCustomReceivers(this.o,g.y,(0,g.z)(function(a){this.fc("Failed to set initial custom receivers: "+g.Ag(a))},this)),this.R("yt-remote-cast2-availability-change",K7(this)),b(!0))},this),(0,g.z)(function(a){this.fc("Failed to initialize API: "+g.Ag(a));
b(!1)},this))};
g.h.KU=function(a,b){J7("Setting connected screen ID: "+a+" -> "+b);if(this.g){var c=this.g.o;if(!a||c&&c.id!=a)J7("Unsetting old screen status: "+this.g.l.friendlyName),L7(this,null)}if(a&&b){if(!this.g){c=v6(this.l.ie(),a);if(!c){J7("setConnectedScreenStatus: Unknown screen.");return}var d=CDa(this,c);d||(J7("setConnectedScreenStatus: Connected receiver not custom..."),d=new window.chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM,this.o.push(d),
window.chrome.cast.setCustomReceivers(this.o,g.y,(0,g.z)(function(a){this.fc("Failed to set initial custom receivers: "+g.Ag(a))},this)));
J7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);L7(this,new H7(this.l,d),!0)}this.g.Lu(b)}else J7("setConnectedScreenStatus: no screen.")};
g.h.LU=function(a){this.ia()?this.fc("Setting connection data on disposed cast v2"):this.g?this.g.Kj(a):this.fc("Setting connection data without a session")};
g.h.OV=function(){this.ia()?this.fc("Stopping session on disposed cast v2"):this.g?(this.g.stop(),L7(this,null)):J7("Stopping non-existing session")};
g.h.requestSession=function(){window.chrome.cast.requestSession((0,g.z)(this.oC,this),(0,g.z)(this.PS,this))};
g.h.V=function(){this.l.unsubscribe("onlineScreenChange",(0,g.z)(this.EE,this));window.chrome&&window.chrome.cast&&window.chrome.cast.removeReceiverActionListener(this.A);g.Ta(g.x("yt.mdx.remote.debug.handlers_")||[],fDa);g.bf(this.g);I7.aa.V.call(this)};
g.h.fc=function(a){n7("Controller",a)};
g.h.pC=function(a,b){this.g==a&&(b||L7(this,null),this.R("yt-remote-cast2-session-change",b))};
g.h.qS=function(a,b){if(!this.ia())if(a)switch(a.friendlyName=window.chrome.cast.unescape(a.friendlyName),J7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case window.chrome.cast.ReceiverAction.CAST:if(this.g)if(this.g.l.label!=a.label)J7("onReceiverAction_: Stopping active receiver: "+this.g.l.friendlyName),this.g.stop();else{J7("onReceiverAction_: Casting to active receiver.");this.g.o&&this.R("yt-remote-cast2-session-change",this.g.o);break}switch(a.receiverType){case window.chrome.cast.ReceiverType.CUSTOM:L7(this,
new H7(this.l,a));break;case window.chrome.cast.ReceiverType.DIAL:L7(this,new G7(this.l,a,this.C));break;case window.chrome.cast.ReceiverType.CAST:L7(this,new F7(this.l,a));break;default:this.fc("Unknown receiver type: "+a.receiverType)}break;case window.chrome.cast.ReceiverAction.STOP:this.g&&this.g.l.label==a.label?this.g.stop():this.fc("Stopping receiver w/o session: "+a.friendlyName)}else this.fc("onReceiverAction_ called without receiver.")};
g.h.pQ=function(a){if(this.ia())return window.Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=window.chrome.cast.ReceiverType.DIAL&&(this.fc("Not DIAL receiver: "+b.friendlyName),b.receiverType=window.chrome.cast.ReceiverType.DIAL);var c=this.g?this.g.l:null;if(!c||c.label!=b.label)return this.fc("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),window.Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=window.chrome.cast.ReceiverType.DIAL){if(this.g.o)return J7("Reselecting dial screen."),
this.R("yt-remote-cast2-session-change",this.g.o),window.Promise.resolve(new window.chrome.cast.DialLaunchResponse(!1));this.fc('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);L7(this,new G7(this.l,b,this.C))}b=this.g;b.F=a;return b.F.appState==window.chrome.cast.DialAppState.RUNNING?new window.Promise((0,g.z)(b.CK,b,(b.F.extraData||{}).screenId||null)):new window.Promise((0,g.z)(b.xs,b))};
g.h.oC=function(a){if(!this.ia()){J7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=window.chrome.cast.ReceiverType.CUSTOM){if(!this.g)if(b.receiverType==window.chrome.cast.ReceiverType.CAST)J7("Got resumed cast session before resumed mdx connection."),b.friendlyName=window.chrome.cast.unescape(b.friendlyName),L7(this,new F7(this.l,b),!0);else{this.fc("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.g.l,d=v6(this.l.ie(),c.label);
d&&q6(d,b.label)&&c.receiverType!=window.chrome.cast.ReceiverType.CAST&&b.receiverType==window.chrome.cast.ReceiverType.CAST&&(J7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.bf(this.g),this.g=new F7(this.l,b),this.g.subscribe("sessionScreen",(0,g.z)(this.pC,this,this.g)),this.g.Kj(null));this.g.Ku(a)}}};
g.h.NV=function(){return this.g?this.g.FE():null};
g.h.PS=function(a){this.ia()||(this.fc("Failed to estabilish a session: "+g.Ag(a)),a.code!=window.chrome.cast.ErrorCode.CANCEL&&L7(this,null))};
g.h.uS=function(a){J7("Receiver availability updated: "+a);if(!this.ia()){var b=K7(this);this.B=a==window.chrome.cast.ReceiverAvailability.AVAILABLE;K7(this)!=b&&this.R("yt-remote-cast2-availability-change",K7(this))}};
g.h.EE=function(){this.ia()||(this.o=DDa(this),J7("Updating custom receivers: "+g.Ag(this.o)),window.chrome.cast.setCustomReceivers(this.o,g.y,(0,g.z)(function(){this.fc("Failed to set custom receivers.")},this)),this.R("yt-remote-cast2-availability-change",K7(this)))};
I7.prototype.setLaunchParams=I7.prototype.LU;I7.prototype.setConnectedScreenStatus=I7.prototype.KU;I7.prototype.stopSession=I7.prototype.OV;I7.prototype.getCastSession=I7.prototype.NV;I7.prototype.requestSession=I7.prototype.requestSession;I7.prototype.init=I7.prototype.init;I7.prototype.dispose=I7.prototype.dispose;var R7=[];g.h=W7.prototype;
g.h.reset=function(a){this.listId="";this.index=-1;this.videoId="";X7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.g=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.l=a.trackData,this.Mf=a.hasPrevious,this.hasNext=a.hasNext,this.F=a.playerTime,this.D=a.playerTimeAt,this.B=a.seekableStart,this.o=a.seekableEnd,this.H=a.duration,this.I=a.loadedTime,this.A=a.liveIngestionTime,this.C=!(0,window.isNaN)(this.A))};
g.h.jb=function(){return 1==this.g};
g.h.isAdPlaying=function(){return 1081==this.g};
g.h.getDuration=function(){return this.C?this.H+Y7(this):this.H};
g.h.clone=function(){return new W7(b8(this))};g.A(d8,g.RF);g.h=d8.prototype;g.h.play=function(){1==this.g?(this.l?this.l.play(null,g.y,j8(this,"play")):i8(this,"play"),h8(this,1,$7(e8(this))),this.R("remotePlayerChange")):f8(this,this.play)};
g.h.pause=function(){1==this.g?(this.l?this.l.pause(null,g.y,j8(this,"pause")):i8(this,"pause"),h8(this,2,$7(e8(this))),this.R("remotePlayerChange")):f8(this,this.pause)};
g.h.AE=function(a){if(1==this.g){if(this.l){var b=e8(this),c=new window.chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=b.jb()||3==b.g?window.chrome.cast.media.ResumeState.PLAYBACK_START:window.chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.l.seek(c,g.y,j8(this,"seekTo",{newTime:a}))}else i8(this,"seekTo",{newTime:a});h8(this,3,a);this.R("remotePlayerChange")}else f8(this,g.Ea(this.AE,a))};
g.h.stop=function(){if(1==this.g){this.l?this.l.stop(null,g.y,j8(this,"stopVideo")):i8(this,"stopVideo");var a=e8(this);a.index=-1;a.videoId="";X7(a);g8(this,a);this.R("remotePlayerChange")}else f8(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=e8(this);if(this.o){if(c.volume!=a){var d=Math.round(a)/100;this.o.setReceiverVolumeLevel(d,(0,g.z)(function(){n7("CP","set receiver volume: "+d)},this),(0,g.z)(function(){this.fc("failed to set receiver volume.")},this))}c.muted!=b&&this.o.setReceiverMuted(b,(0,g.z)(function(){n7("CP","set receiver muted: "+b)},this),(0,g.z)(function(){this.fc("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);i8(this,"setVolume",e)}c.muted=b;c.volume=a;g8(this,c)}else f8(this,g.Ea(this.setVolume,a,b))};
g.h.BD=function(a,b){if(1==this.g){var c=e8(this),d={videoId:a};b&&(c.l={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.Ag(b.style),g.ec(d,c.l));i8(this,"setSubtitlesTrack",d);g8(this,c)}else f8(this,g.Ea(this.BD,a,b))};
g.h.zv=function(a,b){if(1==this.g){i8(this,"setAudioTrack",{videoId:a,audioTrackId:b.Ob.id});var c=e8(this);c.audioTrackId=b.Ob.id;g8(this,c)}else f8(this,g.Ea(this.zv,a,b))};
g.h.zE=function(a,b){if(1==this.g){if(a&&b){var c=e8(this);a8(c,a,b);g8(this,c)}i8(this,"previous")}else f8(this,g.Ea(this.zE,a,b))};
g.h.yE=function(a,b){if(1==this.g){if(a&&b){var c=e8(this);a8(c,a,b);g8(this,c)}i8(this,"next")}else f8(this,g.Ea(this.yE,a,b))};
g.h.Kx=function(){1==this.g?i8(this,"dismissAutoplay"):f8(this,this.Kx)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.R("proxyStateChange",a,this.g)}d8.aa.dispose.call(this)};
g.h.V=function(){QDa(this);this.A=null;this.B.clear();c8(this,null);d8.aa.V.call(this)};
g.h.Av=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.R("proxyStateChange",b,a);if(1==a)for(;!this.B.isEmpty();)g.sC(this.B).apply(this);else 3==a&&this.dispose()}};
g.h.lS=function(a,b){this.R(a,b)};
g.h.MP=function(a){if(!a)this.Ml(null),c8(this,null);else if(this.o.receiver.volume){a=this.o.receiver.volume;var b=e8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)n7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,g8(this,b)}};
g.h.Ml=function(a){n7("CP","Cast media: "+!!a);this.l&&this.l.removeUpdateListener(this.F);if(this.l=a)this.l.addUpdateListener(this.F),RDa(this),this.R("remotePlayerChange")};
g.h.LP=function(a){a?(RDa(this),this.R("remotePlayerChange")):this.Ml(null)};
g.h.YP=function(){var a=NDa();a&&c8(this,a)};
g.h.fc=function(a){n7("CP",a)};g.A(k8,g.RF);g.h=k8.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;g.t(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.t(k)&&(l.currentIndex=k);c&&(this.Xa.listId=c);this.Xa.videoId=d;this.Xa.index=k||0;this.Xa.state=3;Z7(this.Xa,m);this.A="UNSUPPORTED";l8("Connecting with setPlaylist and params: "+g.Ag(l));this.g.connect({method:"setPlaylist",
params:g.Ag(l)},a,mCa())}else l8("Connecting without params"),this.g.connect({},a,mCa());TDa(this)};
g.h.dispose=function(){this.ia()||(this.R("beforeDispose"),m8(this,3));k8.aa.dispose.call(this)};
g.h.V=function(){n8(this);p8(this);o8(this);g.aE(this.H);this.H=window.NaN;g.aE(this.I);this.I=window.NaN;this.o=null;g.BF(this.U);this.U.length=0;this.g.dispose();k8.aa.V.call(this);this.A=this.D=this.l=this.Xa=this.g=null};
g.h.NI=function(){this.C(2)};
g.h.QP=function(){l8("Channel opened");this.N&&(this.N=!1,o8(this),this.L=g.ZD((0,g.z)(function(){l8("Timing out waiting for a screen.");this.C(1)},this),15E3));
qCa(cDa(this.g),this.Z)};
g.h.NP=function(){l8("Channel closed");(0,window.isNaN)(this.B)?A6(!0):A6();this.dispose()};
g.h.OP=function(a){A6();(0,window.isNaN)(this.F())?(l8("Channel error: "+a+" without reconnection"),this.dispose()):(this.N=!0,l8("Channel error: "+a+" with reconnection in "+this.F()+" ms"),m8(this,2))};
g.h.PP=function(a){a.params?l8("Received: action="+a.action+", params="+g.Ag(a.params)):l8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=g.Yw(a.params.devices);this.l=(0,g.G)(a,function(a){return new o6(a)});
a=!!g.Ja(this.l,function(a){return"LOUNGE_SCREEN"==a.type});
WDa(this,a);break;case "loungeScreenDisconnected":g.Ua(this.l,function(a){return"LOUNGE_SCREEN"==a.type});
WDa(this,!1);break;case "remoteConnected":var b=new o6(g.Yw(a.params.device));g.Ja(this.l,function(a){return b?a.id==b.id:!1})||g.Ra(this.l,b);
break;case "remoteDisconnected":b=new o6(g.Yw(a.params.device));g.Ua(this.l,function(a){return b?a.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":YDa(this,a);break;case "nowPlaying":$Da(this,a);break;case "onStateChange":ZDa(this,a);break;case "onAdStateChange":aEa(this,a);break;case "onVolumeChanged":bEa(this,a);break;case "onSubtitlesTrackChanged":XDa(this,a);break;case "nowAutoplaying":cEa(this,a);break;case "autoplayDismissed":this.R("autoplayDismissed");break;case "autoplayUpNext":this.D=a.params.videoId||null;this.R("autoplayUpNext",this.D);break;case "onAutoplayModeChanged":this.A=
a.params.autoplayMode;this.R("autoplayModeChange",this.A);"DISABLED"==this.A&&this.R("autoplayDismissed");break;case "onHasPreviousNextChanged":dEa(this,a);break;case "requestAssistedSignIn":this.R("assistedSignInRequested",a.params.authCode);break;default:l8("Unrecognized action: "+a.action)}};
g.h.uU=function(){if(this.o){var a=this.o;this.o=null;this.Xa.videoId!=a&&q8(this,"getNowPlaying")}};
k8.prototype.subscribe=k8.prototype.subscribe;k8.prototype.unsubscribeByKey=k8.prototype.Md;k8.prototype.fa=function(){var a=3;this.ia()||(a=0,(0,window.isNaN)(this.F())?i7(this.g)&&(0,window.isNaN)(this.B)&&(a=1):a=2);return a};
k8.prototype.getProxyState=k8.prototype.fa;k8.prototype.C=function(a){l8("Disconnecting with "+a);n8(this);this.R("beforeDisconnect",a);1==a&&A6();dDa(this.g,a);this.dispose()};
k8.prototype.disconnect=k8.prototype.C;k8.prototype.ea=function(){var a=this.Xa;this.o&&(a=this.Xa.clone(),a8(a,this.o,a.index));return b8(a)};
k8.prototype.getPlayerContextData=k8.prototype.ea;
k8.prototype.ma=function(a){var b=new W7(a);b.videoId&&b.videoId!=this.Xa.videoId&&(this.o=b.videoId,g.aE(this.H),this.H=g.ZD((0,g.z)(this.uU,this),5E3));var c=[];this.Xa.listId==b.listId&&this.Xa.videoId==b.videoId&&this.Xa.index==b.index||c.push("remoteQueueChange");this.Xa.g==b.g&&this.Xa.volume==b.volume&&this.Xa.muted==b.muted&&$7(this.Xa)==$7(b)&&g.Ag(this.Xa.l)==g.Ag(b.l)||c.push("remotePlayerChange");this.Xa.reset(a);(0,g.B)(c,function(a){this.R(a)},this)};
k8.prototype.setPlayerContextData=k8.prototype.ma;k8.prototype.X=function(){var a=this.g.C.id,b=g.Ja(this.l,function(b){return"REMOTE_CONTROL"==b.type&&b.id!=a});
return b?b.id:""};
k8.prototype.getOtherConnectedRemoteId=k8.prototype.X;k8.prototype.F=function(){var a=this.g;return a.l.isActive()?a.l.l-(0,g.F)():window.NaN};
k8.prototype.getReconnectTimeout=k8.prototype.F;k8.prototype.Y=function(){return this.A||"UNSUPPORTED"};
k8.prototype.getAutoplayMode=k8.prototype.Y;k8.prototype.ba=function(){return this.D||""};
k8.prototype.getAutoplayVideoId=k8.prototype.ba;k8.prototype.ra=function(){if(!(0,window.isNaN)(this.F())){var a=this.g.l;g.au(a.g);a.start()}};
k8.prototype.reconnect=k8.prototype.ra;k8.prototype.ha=function(a,b){q8(this,a,b);VDa(this)};
k8.prototype.sendMessage=k8.prototype.ha;g.A(r8,r7);g.h=r8.prototype;g.h.ie=function(a){return this.dd.$_gs(a)};
g.h.contains=function(a){return!!this.dd.$_c(a)};
g.h.get=function(a){return this.dd.$_g(a)};
g.h.start=function(){this.dd.$_st()};
g.h.add=function(a,b,c){this.dd.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.dd.$_r(a,b,c)};
g.h.Hp=function(a,b,c,d){this.dd.$_un(a,b,c,d)};
g.h.V=function(){for(var a=0,b=this.l.length;a<b;++a)this.dd.$_ubk(this.l[a]);this.l.length=0;this.dd=null;r8.aa.V.call(this)};
g.h.KV=function(){this.R("screenChange")};
g.h.MR=function(){this.R("onlineScreenChange")};
A7.prototype.$_st=A7.prototype.start;A7.prototype.$_gspc=A7.prototype.LV;A7.prototype.$_gsppc=A7.prototype.DE;A7.prototype.$_c=A7.prototype.contains;A7.prototype.$_g=A7.prototype.get;A7.prototype.$_a=A7.prototype.add;A7.prototype.$_un=A7.prototype.Hp;A7.prototype.$_r=A7.prototype.remove;A7.prototype.$_gs=A7.prototype.ie;A7.prototype.$_gos=A7.prototype.CE;A7.prototype.$_s=A7.prototype.subscribe;A7.prototype.$_ubk=A7.prototype.Md;var s8=null,t8=null,I8=null,x8=[];g.p(J8,g.K);g.h=J8.prototype;
g.h.V=function(){g.K.prototype.V.call(this);this.A.stop();this.B.stop();this.K.stop();this.N();this.g.unsubscribe("proxyStateChange",this.mC,this);this.g.unsubscribe("remotePlayerChange",this.Pl,this);this.g.unsubscribe("remoteQueueChange",this.Lo,this);this.g.unsubscribe("autoplayUpNext",this.JB,this);this.g.unsubscribe("previousNextChange",this.jC,this);this.g.unsubscribe("nowAutoplaying",this.bC,this);this.g.unsubscribe("autoplayDismissed",this.IB,this);this.g=this.F=null};
g.h.KA=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.g.g)if(M8(this)){if(!e8(this.g).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":e8(this.g).jb()?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.I.sj(c[0],c[1]);break;case "control_subtitles_set_track":N8(this,c[0]);break;case "control_set_audio_track":c=c[0],M8(this)&&this.g.zv(this.l.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.l.getCurrentTime();O8(this,0==c?void 0:c);break;case "control_seek":O8(this,c[0]);break;case "control_subtitles_set_track":N8(this,c[0]);break;case "control_set_audio_track":c=c[0],M8(this)&&this.g.zv(this.l.getVideoData(1).videoId,c)}};
g.h.KP=function(a){this.K.II(a)};
g.h.nV=function(a){this.KA("control_subtitles_set_track",g.Xb(a)?null:a)};
g.h.QD=function(){var a=this.l.xc("captions","track");g.Xb(a)||N8(this,a)};
g.h.ZB=function(a){if(M8(this)){this.g.unsubscribe("remotePlayerChange",this.Pl,this);var b=Math.round(a.volume);a=!!a.muted;var c=e8(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.L.start();this.g.subscribe("remotePlayerChange",this.Pl,this)}};
g.h.fR=function(){g.Xb(this.C)||pEa(this,this.C);this.D=!1};
g.h.mC=function(a,b){this.B.stop();2==b&&this.ND()};
g.h.Pl=function(){if(M8(this)){this.A.stop();var a=e8(this.g);switch(a.g){case 1081:case 1:L8(this,new g.DP(8));this.MD();break;case 1085:case 3:L8(this,new g.DP(9));break;case 1083:case 0:L8(this,new g.DP(2));this.I.stop();K8(this,this.l.getVideoData().lengthSeconds);break;case 1084:L8(this,new g.DP(4));break;case 2:L8(this,new g.DP(4));K8(this,$7(a));break;case -1:L8(this,new g.DP(64));break;case -1E3:a={errorCode:"mdx.remoteerror",message:g.T("YTP_MDX_PLAYER_ERROR")},L8(this,new g.DP(128,a))}a=
e8(this.g).l;var b=this.C;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.C=a,pEa(this,a));a=e8(this.g);-1==a.volume||Math.round(this.l.getVolume())==a.volume&&this.l.isMuted()==a.muted||this.L.isActive()||this.oE()}else oEa(this)};
g.h.jC=function(){this.l.R("mdxpreviousnextchange")};
g.h.Lo=function(){M8(this)||oEa(this)};
g.h.TH=function(){this.g.Kx()};
g.h.JB=function(a){a&&(a=g.oE("/watch_queue_ajax",{method:"GET",Xc:{action_get_watch_queue_item:1,video_id:a},onSuccess:(0,g.z)(this.qT,this)}))&&(this.N=(0,g.z)(a.abort,a))};
g.h.qT=function(a,b){var c=new g.tO({videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.l.R("mdxautoplayupnext",c)};
g.h.bC=function(a){(0,window.isNaN)(a)||this.l.R("mdxnowautoplaying",a)};
g.h.IB=function(){this.l.R("mdxautoplaycanceled")};
g.h.KN=function(a,b){-1==e8(this.g).g?O8(this,a):b&&this.g.AE(a)};
g.h.oE=function(){if(M8(this)){var a=e8(this.g);this.o.Ca(this.U);a.muted?this.l.mute():this.l.Xf();this.l.setVolume(a.volume);this.U=this.o.O(this.l,"onVolumeChange",this.ZB)}};
g.h.MD=function(){this.A.stop();if(!this.g.ia()){var a=e8(this.g);a.jb()&&L8(this,new g.DP(8));K8(this,$7(a));this.A.start()}};
g.h.ND=function(){this.B.stop();this.A.stop();var a=this.g.A.getReconnectTimeout();2==this.g.g&&!(0,window.isNaN)(a)&&this.B.start()};g.p(P8,g.U);P8.prototype.B=function(a){rEa(this,a.state)};g.p(Q8,g.JZ);Q8.prototype.K=function(){var a=this.o.xc("remote","receivers");a&&1<a.length&&!this.o.xc("remote","quickCast")?(this.H=g.jb(a,this.C,this),g.KZ(this,(0,g.G)(a,this.C)),a=this.o.xc("remote","currentReceiver"),this.pf(this.C(a)),this.enable(!0)):this.enable(!1)};
Q8.prototype.C=function(a){return a.key};
Q8.prototype.nf=function(a){return"cast-selector-receiver"==a?g.T("YTP_MDX_CAST_SELECTOR"):this.H[a].name};
Q8.prototype.td=function(a){g.JZ.prototype.td.call(this,a);this.o.Jd("remote","currentReceiver",this.H[a]);this.B.Pb()};g.p(R8,g.eV);g.h=R8.prototype;g.h.create=function(){iEa(g.JM(g.W(this.g)));this.C.push(g.cG("yt-remote-before-disconnect",this.GP,this));this.C.push(g.cG("yt-remote-connection-change",this.vS,this));this.C.push(g.cG("yt-remote-receiver-availability-change",this.kC,this));this.C.push(g.cG("yt-remote-auto-connect",this.tS,this));this.C.push(g.cG("yt-remote-receiver-resumed",this.sS,this));this.kC()};
g.h.load=function(){this.g.Dt();g.eV.prototype.load.call(this);this.B=new J8(this,this.g,this.l);var a=(a=nEa())?a.currentTime:0;var b=H8()?new d8(C8(),void 0):null;0==a&&b&&(a=$7(e8(b)));0!=a&&(this.H=a||0,this.g.R("progresssync",a,void 0));qEa(this,this.D,this.D);g.$_(this.g.app,6)};
g.h.unload=function(){this.g.R("mdxautoplaycanceled");this.A=this.o;g.cf(this.B,this.l);this.l=this.B=null;g.eV.prototype.unload.call(this);g.$_(this.g.app,5)};
g.h.V=function(){g.dG(this.C);g.eV.prototype.V.call(this)};
g.h.Fl=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.B.KA.apply(this.B,[a].concat(g.oa(c)))};
g.h.EI=function(){return this.loaded?this.B.suggestion:null};
g.h.Mf=function(){return this.l?e8(this.l).Mf:!1};
g.h.hasNext=function(){return this.l?e8(this.l).hasNext:!1};
g.h.getCurrentTime=function(){return this.H};
g.h.yN=function(){var a=e8(this.l),b=this.g.getVideoData();return{allowSeeking:this.g.fd(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.C?a.A+Y7(a):a.A,isPeggedToLive:1>=(a.C?a.o+Y7(a):a.o)-this.getCurrentTime(),loaded:a.I,seekableEnd:a.C?a.o+Y7(a):a.o,seekableStart:0<a.B?a.B+Y7(a):a.B}};
g.h.zN=function(){this.l&&this.l.yE()};
g.h.AN=function(){this.l&&this.l.zE()};
g.h.GP=function(a){1==a&&(this.I=this.l?e8(this.l):null)};
g.h.vS=function(){var a=H8()?new d8(C8(),void 0):null;if(a){var b=this.A;this.loaded&&this.unload();this.l=a;this.I=null;b.key!=this.o.key&&(this.A=b,this.load())}else g.bf(this.l),this.l=null,this.loaded&&(this.unload(),(a=this.I)&&a.videoId==this.g.getVideoData().videoId&&this.g.nA(a.videoId,$7(a)));this.g.R("videodatachange","newdata",this.g.getVideoData(),3)};
g.h.kC=function(){this.F=[this.o].concat(kEa());var a=D8()||this.o;S8(this,a);this.g.ua("onMdxReceiversChange")};
g.h.tS=function(){var a=D8();S8(this,a)};
g.h.sS=function(){this.A=D8()};
g.h.xN=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.F;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?U7():S8(this,b)),this.loaded?this.A:this.o;case "quickCast":return 2==this.F.length&&"cast-selector-receiver"==this.F[1].key?(b&&U7(),!0):!1}};
g.h.BN=function(){i8(this.l,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.Nc=function(){return!1};g.YX.remote=R8;})(_yt_player);
